// <auto-generated />
using System;
using BookShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace P01_BookShopSystem.Migrations
{
    [DbContext(typeof(BookShopContext))]
    partial class BookShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookShop.Models.Author", b =>
                {
                    b.Property<Guid>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = new Guid("9fd811a2-1205-49be-855b-ae5870a35ab0"),
                            FirstName = "Cordelia",
                            LastName = "Keebler"
                        },
                        new
                        {
                            AuthorId = new Guid("db301584-8072-4526-abef-edceaa0130b9"),
                            FirstName = "Armand",
                            LastName = "Rice"
                        },
                        new
                        {
                            AuthorId = new Guid("d6bb3603-8740-478a-b489-0d806456da32"),
                            FirstName = "Garth",
                            LastName = "Effertz"
                        },
                        new
                        {
                            AuthorId = new Guid("d0faa616-0eae-4009-8c84-65602894e98e"),
                            FirstName = "Elian",
                            LastName = "Stoltenberg"
                        },
                        new
                        {
                            AuthorId = new Guid("4e0287dc-f475-4d5a-8719-9790b932f29a"),
                            FirstName = "Elroy",
                            LastName = "Brakus"
                        },
                        new
                        {
                            AuthorId = new Guid("5f85877d-aa9f-4a82-863c-99ceec21ef6a"),
                            FirstName = "Ocie",
                            LastName = "Schroeder"
                        },
                        new
                        {
                            AuthorId = new Guid("2428cd72-2f73-454b-a9a5-80eac882d8e0"),
                            FirstName = "Jacquelyn",
                            LastName = "Connelly"
                        },
                        new
                        {
                            AuthorId = new Guid("5e6c8582-ca0b-4912-a67d-8c8379065e3a"),
                            FirstName = "Lydia",
                            LastName = "Wisoky"
                        },
                        new
                        {
                            AuthorId = new Guid("ff7601bc-2d78-42d4-82da-b581f7300ce3"),
                            FirstName = "Bessie",
                            LastName = "Jacobi"
                        },
                        new
                        {
                            AuthorId = new Guid("10164bef-3e37-447f-9f47-850fc004c3ac"),
                            FirstName = "Effie",
                            LastName = "Huels"
                        });
                });

            modelBuilder.Entity("BookShop.Models.Book", b =>
                {
                    b.Property<Guid>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgeRestriction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Copies")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EditionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BookId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = new Guid("8dc3408d-0c18-40e6-a88c-dce271171c8d"),
                            AgeRestriction = "Teen",
                            AuthorId = new Guid("9fd811a2-1205-49be-855b-ae5870a35ab0"),
                            Copies = 579,
                            Description = "Et voluptas distinctio explicabo velit quam. Veniam excepturi occaecati et impedit omnis voluptates aut quia inventore. Consequatur in in et libero enim labore voluptas sed.",
                            EditionType = "Promo",
                            Price = 354.655867036279807m,
                            ReleaseDate = new DateTime(2014, 12, 30, 20, 34, 53, 151, DateTimeKind.Local).AddTicks(5360),
                            Title = "et"
                        },
                        new
                        {
                            BookId = new Guid("d7a1bff5-b2bd-491e-a2e3-d746e09e67b0"),
                            AgeRestriction = "Minor",
                            AuthorId = new Guid("9fd811a2-1205-49be-855b-ae5870a35ab0"),
                            Copies = 718,
                            Description = "Natus aut ut quas cum quia qui neque id aut. Ullam vel aut sed sequi pariatur. Architecto ex illum ullam corporis eos. Dolorum quis qui dignissimos debitis aut dolore deserunt adipisci magni.",
                            EditionType = "Promo",
                            Price = 928.961308723369708m,
                            ReleaseDate = new DateTime(2017, 12, 5, 8, 51, 54, 518, DateTimeKind.Local).AddTicks(6506),
                            Title = "deleniti"
                        },
                        new
                        {
                            BookId = new Guid("5838fa98-310c-4ad7-bad8-df0fb43e2125"),
                            AgeRestriction = "Adult",
                            AuthorId = new Guid("2428cd72-2f73-454b-a9a5-80eac882d8e0"),
                            Copies = 905,
                            Description = "Et neque consequatur minus beatae sint tempore dolor. Iusto et doloribus in ut et eaque vitae suscipit. Voluptatem consequatur maxime ipsam. Occaecati explicabo aut id sint natus ut voluptas.",
                            EditionType = "Normal",
                            Price = 540.558009471115306m,
                            ReleaseDate = new DateTime(2023, 2, 1, 2, 16, 47, 658, DateTimeKind.Local).AddTicks(4544),
                            Title = "vitae"
                        },
                        new
                        {
                            BookId = new Guid("e58136b9-063c-42ee-bcb7-3da05a04fef5"),
                            AgeRestriction = "Teen",
                            AuthorId = new Guid("10164bef-3e37-447f-9f47-850fc004c3ac"),
                            Copies = 960,
                            Description = "Aut tempora nulla accusamus ut ut ullam accusantium. Voluptate et quia. Optio ab non beatae ipsa doloribus alias. Nulla nam beatae debitis quo. Ut quidem et ab consequatur. Culpa earum voluptatem esse.",
                            EditionType = "Promo",
                            Price = 826.656071492158795m,
                            ReleaseDate = new DateTime(2014, 7, 24, 18, 27, 22, 150, DateTimeKind.Local).AddTicks(2864),
                            Title = "dolores"
                        },
                        new
                        {
                            BookId = new Guid("ba562694-2437-4798-b2da-061da03cedca"),
                            AgeRestriction = "Teen",
                            AuthorId = new Guid("4e0287dc-f475-4d5a-8719-9790b932f29a"),
                            Copies = 581,
                            Description = "Sunt at quis distinctio enim et molestiae qui eos sint. Dolor inventore dolorem qui ex vel provident occaecati nesciunt. Dolorum ab molestiae dolorem magnam. Cupiditate nesciunt sed quia nam quis eos. Animi voluptatem omnis aliquam ad iure ut.",
                            EditionType = "Normal",
                            Price = 41.5588173676316839m,
                            ReleaseDate = new DateTime(2018, 11, 8, 15, 24, 21, 868, DateTimeKind.Local).AddTicks(8691),
                            Title = "enim"
                        },
                        new
                        {
                            BookId = new Guid("d738305d-79f6-4239-828c-1fe80ba48eb1"),
                            AgeRestriction = "Adult",
                            AuthorId = new Guid("2428cd72-2f73-454b-a9a5-80eac882d8e0"),
                            Copies = 555,
                            Description = "Explicabo rerum nulla accusantium accusantium ea nam aut ipsam sint. Consequatur cupiditate at odio ratione eaque sunt. Quia dicta sint quo recusandae. Culpa a error ut quibusdam dignissimos et voluptatum sequi. Possimus et perspiciatis non non. Commodi quia modi et nesciunt iure aut est omnis aut.",
                            EditionType = "Gold",
                            Price = 499.832963792217694m,
                            ReleaseDate = new DateTime(2010, 9, 23, 1, 52, 32, 500, DateTimeKind.Local).AddTicks(9199),
                            Title = "modi"
                        },
                        new
                        {
                            BookId = new Guid("b7fc3d74-ec43-412c-a59c-3916ece021b7"),
                            AgeRestriction = "Adult",
                            AuthorId = new Guid("d0faa616-0eae-4009-8c84-65602894e98e"),
                            Copies = 437,
                            Description = "Reiciendis omnis neque debitis sint sed. Vel eos molestiae autem perspiciatis. Necessitatibus assumenda eum officia fuga. Exercitationem iste et odio asperiores. Praesentium esse expedita dicta et est iste est molestias. Quae saepe ducimus.",
                            EditionType = "Promo",
                            Price = 936.442379991154096m,
                            ReleaseDate = new DateTime(2008, 7, 26, 13, 27, 5, 690, DateTimeKind.Local).AddTicks(6423),
                            Title = "et"
                        },
                        new
                        {
                            BookId = new Guid("853c774d-de1f-42c3-b30a-43baba5125d0"),
                            AgeRestriction = "Minor",
                            AuthorId = new Guid("5e6c8582-ca0b-4912-a67d-8c8379065e3a"),
                            Copies = 823,
                            Description = "Adipisci repudiandae inventore hic necessitatibus sed. Illum corrupti in sint sed et quia. Similique nihil ut dicta fugit. Iusto velit corrupti dolorem sed voluptate. Odit reprehenderit et. Amet ex quae repellendus quia nam est vel.",
                            EditionType = "Normal",
                            Price = 268.719754137017104m,
                            ReleaseDate = new DateTime(2017, 6, 18, 4, 30, 57, 49, DateTimeKind.Local).AddTicks(8848),
                            Title = "ut"
                        },
                        new
                        {
                            BookId = new Guid("3d02d709-0c74-469a-a4ed-f585ddc53682"),
                            AgeRestriction = "Adult",
                            AuthorId = new Guid("d0faa616-0eae-4009-8c84-65602894e98e"),
                            Copies = 34,
                            Description = "Quos necessitatibus magni voluptatem aut in iste. Amet rem iure commodi aliquam corporis ut tempore ducimus id. Deleniti fuga non voluptatem sint pariatur occaecati voluptatem. Consequatur doloremque iusto nisi eius. Aut possimus inventore quaerat voluptas et dignissimos id exercitationem alias. Et et placeat hic ducimus corrupti rem asperiores.",
                            EditionType = "Normal",
                            Price = 777.000494680686361m,
                            ReleaseDate = new DateTime(2018, 8, 16, 22, 25, 36, 810, DateTimeKind.Local).AddTicks(4559),
                            Title = "sint"
                        },
                        new
                        {
                            BookId = new Guid("b4d39db9-925e-4200-a787-0525e9f6b556"),
                            AgeRestriction = "Teen",
                            AuthorId = new Guid("4e0287dc-f475-4d5a-8719-9790b932f29a"),
                            Copies = 819,
                            Description = "Aperiam labore corrupti. Et dolor veritatis accusamus iusto molestias ullam repellat nemo ullam. Doloribus quo est est. Expedita quia adipisci. Quae quia consequuntur reprehenderit nihil.",
                            EditionType = "Normal",
                            Price = 340.744257810638209m,
                            ReleaseDate = new DateTime(2014, 8, 10, 17, 51, 54, 635, DateTimeKind.Local).AddTicks(4390),
                            Title = "hic"
                        });
                });

            modelBuilder.Entity("BookShop.Models.BookCategory", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BookId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("BookCategory");

                    b.HasData(
                        new
                        {
                            BookId = new Guid("5838fa98-310c-4ad7-bad8-df0fb43e2125"),
                            CategoryId = new Guid("daa5565b-beec-414f-8c11-aee307c54948")
                        },
                        new
                        {
                            BookId = new Guid("b7fc3d74-ec43-412c-a59c-3916ece021b7"),
                            CategoryId = new Guid("daa5565b-beec-414f-8c11-aee307c54948")
                        },
                        new
                        {
                            BookId = new Guid("3d02d709-0c74-469a-a4ed-f585ddc53682"),
                            CategoryId = new Guid("76ecbc80-84e4-4452-a7b3-9b458ea89fc1")
                        },
                        new
                        {
                            BookId = new Guid("b7fc3d74-ec43-412c-a59c-3916ece021b7"),
                            CategoryId = new Guid("f581664e-0b5a-4b5f-80d2-af727b9bc25b")
                        },
                        new
                        {
                            BookId = new Guid("5838fa98-310c-4ad7-bad8-df0fb43e2125"),
                            CategoryId = new Guid("fbcf061c-d7e8-4736-a668-3fefdf27c13f")
                        });
                });

            modelBuilder.Entity("BookShop.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("4588d245-7010-4897-a005-5fc75e7b1eea"),
                            Name = "Home & Tools"
                        },
                        new
                        {
                            CategoryId = new Guid("63ac623b-5de0-4655-824f-191928d321ce"),
                            Name = "Computers & Home"
                        },
                        new
                        {
                            CategoryId = new Guid("952b2273-ba70-4466-a713-976fc7057c0e"),
                            Name = "Electronics, Sports & Computers"
                        },
                        new
                        {
                            CategoryId = new Guid("70fb7131-61e0-42bd-9131-2e2b3bd12243"),
                            Name = "Sports, Grocery & Clothing"
                        },
                        new
                        {
                            CategoryId = new Guid("daa5565b-beec-414f-8c11-aee307c54948"),
                            Name = "Books"
                        },
                        new
                        {
                            CategoryId = new Guid("36350a71-d729-4e1e-86e6-beb9fa28cdfa"),
                            Name = "Grocery, Outdoors & Computers"
                        },
                        new
                        {
                            CategoryId = new Guid("061019fa-6d4e-4413-a52b-a83316ac2eb3"),
                            Name = "Baby & Baby"
                        },
                        new
                        {
                            CategoryId = new Guid("76ecbc80-84e4-4452-a7b3-9b458ea89fc1"),
                            Name = "Games"
                        },
                        new
                        {
                            CategoryId = new Guid("fbcf061c-d7e8-4736-a668-3fefdf27c13f"),
                            Name = "Shoes & Movies"
                        },
                        new
                        {
                            CategoryId = new Guid("f581664e-0b5a-4b5f-80d2-af727b9bc25b"),
                            Name = "Computers"
                        });
                });

            modelBuilder.Entity("BookShop.Models.Book", b =>
                {
                    b.HasOne("BookShop.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("BookShop.Models.BookCategory", b =>
                {
                    b.HasOne("BookShop.Models.Book", "Book")
                        .WithMany("BookCategories")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookShop.Models.Category", "Category")
                        .WithMany("BookCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BookShop.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookShop.Models.Book", b =>
                {
                    b.Navigation("BookCategories");
                });

            modelBuilder.Entity("BookShop.Models.Category", b =>
                {
                    b.Navigation("BookCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
