// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P03_SalesDatabase.Data;

#nullable disable

namespace P03_SalesDatabase.Migrations
{
    [DbContext(typeof(SalesContext))]
    [Migration("20230415094718_ProductsAddColumnDescription")]
    partial class ProductsAddColumnDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("P03_SalesDatabase.Data.Models.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreditCardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = new Guid("80c5a775-b966-4f47-a9e4-7032dea2b047"),
                            CreditCardNumber = "6759-9158-6976-8551-597",
                            Email = "Milton.West@yahoo.com",
                            Name = "Milton West"
                        },
                        new
                        {
                            CustomerId = new Guid("8e7c619f-a31f-43fb-8d29-630a2eb3b52b"),
                            CreditCardNumber = "3529-1331-6415-2634",
                            Email = "Garrett17@yahoo.com",
                            Name = "Garrett Rowe"
                        },
                        new
                        {
                            CustomerId = new Guid("5fa32538-7d44-4f21-8068-c0464bdd2ef2"),
                            CreditCardNumber = "4809848351011",
                            Email = "Ernest.Zieme@hotmail.com",
                            Name = "Ernest Zieme"
                        },
                        new
                        {
                            CustomerId = new Guid("d0589296-b3fc-487d-9a08-62134543865b"),
                            CreditCardNumber = "6759-4999-8496-3227",
                            Email = "Naomi75@hotmail.com",
                            Name = "Naomi Shields"
                        },
                        new
                        {
                            CustomerId = new Guid("1d30cc86-7af1-4c30-b5c0-2a343d725a32"),
                            CreditCardNumber = "3551-0032-5902-2912",
                            Email = "Geoffrey3@yahoo.com",
                            Name = "Geoffrey Haag"
                        },
                        new
                        {
                            CustomerId = new Guid("0cb9f7a9-b855-4ed0-9ce3-b0ab6231490b"),
                            CreditCardNumber = "6767-1267-0538-9644",
                            Email = "Renee_Ledner@gmail.com",
                            Name = "Renee Ledner"
                        },
                        new
                        {
                            CustomerId = new Guid("763e24cd-311a-4da7-8b77-fca2d90ac377"),
                            CreditCardNumber = "3403-862733-83077",
                            Email = "Hope_Fadel22@hotmail.com",
                            Name = "Hope Fadel"
                        },
                        new
                        {
                            CustomerId = new Guid("fe4ccf93-bf41-4100-b448-97299028dd7a"),
                            CreditCardNumber = "3717-859936-58142",
                            Email = "Faith_Hettinger95@gmail.com",
                            Name = "Faith Hettinger"
                        },
                        new
                        {
                            CustomerId = new Guid("e3eae361-cab6-4747-ac79-de946cd51640"),
                            CreditCardNumber = "4441925733463",
                            Email = "Leona.Gaylord@yahoo.com",
                            Name = "Leona Gaylord"
                        },
                        new
                        {
                            CustomerId = new Guid("4849cfd9-69fd-404c-91ab-bccf449730d2"),
                            CreditCardNumber = "5447-5427-3434-7090",
                            Email = "Jean_Hirthe@yahoo.com",
                            Name = "Jean Hirthe"
                        },
                        new
                        {
                            CustomerId = new Guid("8c2b163a-2abc-49c6-a21a-325170f54185"),
                            CreditCardNumber = "6771-8991-7378-1484",
                            Email = "Dixie_Block26@hotmail.com",
                            Name = "Dixie Block"
                        },
                        new
                        {
                            CustomerId = new Guid("dc10c621-dd52-401d-b010-6b32572bc2ff"),
                            CreditCardNumber = "6379-7789-3401-3591",
                            Email = "Robyn_Skiles36@yahoo.com",
                            Name = "Robyn Skiles"
                        },
                        new
                        {
                            CustomerId = new Guid("5d71c306-bfbd-49f8-a771-c80f3df1abf2"),
                            CreditCardNumber = "3408-452303-94444",
                            Email = "Jane.Schmitt@hotmail.com",
                            Name = "Jane Schmitt"
                        },
                        new
                        {
                            CustomerId = new Guid("b72b4e86-e813-4149-ab8c-fa04a8b5c28c"),
                            CreditCardNumber = "6767-7633-2674-1275-07",
                            Email = "Rufus_Murray30@gmail.com",
                            Name = "Rufus Murray"
                        },
                        new
                        {
                            CustomerId = new Guid("8f9dc5e1-c2c6-42e7-a2fd-2b78dcd59ce2"),
                            CreditCardNumber = "3034-124371-9848",
                            Email = "Nancy.Lemke@hotmail.com",
                            Name = "Nancy Lemke"
                        },
                        new
                        {
                            CustomerId = new Guid("6707c0f2-2ea3-42a3-b90d-65d88e5942b4"),
                            CreditCardNumber = "5456-1508-7622-9452",
                            Email = "Shannon_Ryan@gmail.com",
                            Name = "Shannon Ryan"
                        },
                        new
                        {
                            CustomerId = new Guid("0e63364d-0fbe-4709-9a1a-afe6ac7b7028"),
                            CreditCardNumber = "4149429032890",
                            Email = "Mark.Zulauf35@yahoo.com",
                            Name = "Mark Zulauf"
                        },
                        new
                        {
                            CustomerId = new Guid("143a6814-579e-4898-90dc-32459715675b"),
                            CreditCardNumber = "5110-8582-2841-5821",
                            Email = "Hugh56@gmail.com",
                            Name = "Hugh Littel"
                        },
                        new
                        {
                            CustomerId = new Guid("dbcdf2a8-3bf9-45df-8f4b-312236e6d0c3"),
                            CreditCardNumber = "6767-4951-0539-3823",
                            Email = "Dana49@yahoo.com",
                            Name = "Dana Sawayn"
                        },
                        new
                        {
                            CustomerId = new Guid("ccfd8498-127a-4326-9c20-88a9624f4b41"),
                            CreditCardNumber = "3702-142429-42422",
                            Email = "Linda_Hartmann91@gmail.com",
                            Name = "Linda Hartmann"
                        });
                });

            modelBuilder.Entity("P03_SalesDatabase.Data.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasDefaultValue("No description");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("b225ef06-9127-4caf-83e8-0c79b6a9dd9c"),
                            Name = "Fantastic Soft Computer",
                            Price = 7508.107787716120000m,
                            Quantity = 721.56256f
                        },
                        new
                        {
                            ProductId = new Guid("390161b6-8098-486c-95ae-8fb18327acef"),
                            Name = "Small Rubber Towels",
                            Price = 6148.59587338330000m,
                            Quantity = 791.2883f
                        },
                        new
                        {
                            ProductId = new Guid("b727fbcf-308c-4541-9e5f-a6a99c266137"),
                            Name = "Small Soft Car",
                            Price = 2425.155345856720000m,
                            Quantity = 594.31445f
                        },
                        new
                        {
                            ProductId = new Guid("86ec2573-3aff-4602-88d5-27ec7ff15f28"),
                            Name = "Generic Cotton Chicken",
                            Price = 6478.547860343920000m,
                            Quantity = 618.7115f
                        },
                        new
                        {
                            ProductId = new Guid("7435d83b-bd82-4d34-a3c3-396ee701db9e"),
                            Name = "Tasty Metal Chicken",
                            Price = 769.0837182970590000m,
                            Quantity = 971.50977f
                        },
                        new
                        {
                            ProductId = new Guid("a12aaaae-24ae-4695-820d-5995174630f7"),
                            Name = "Handcrafted Soft Chair",
                            Price = 827.9090010094720000m,
                            Quantity = 943.22516f
                        },
                        new
                        {
                            ProductId = new Guid("77e87ed2-93e2-49c7-ab2e-d6ded7c6cd24"),
                            Name = "Handmade Steel Cheese",
                            Price = 3662.058424883210000m,
                            Quantity = 923.27435f
                        },
                        new
                        {
                            ProductId = new Guid("7201abd4-8a05-428f-a18e-979acc095e61"),
                            Name = "Licensed Granite Towels",
                            Price = 3101.742079616540000m,
                            Quantity = 287.0193f
                        },
                        new
                        {
                            ProductId = new Guid("9df986b4-e049-4092-a6de-ced84af9b186"),
                            Name = "Handmade Concrete Salad",
                            Price = 2219.506012757110000m,
                            Quantity = 203.96568f
                        },
                        new
                        {
                            ProductId = new Guid("64064e0a-9ca4-4cca-bc25-d47217d6e357"),
                            Name = "Refined Wooden Hat",
                            Price = 1488.926560587660000m,
                            Quantity = 121.8415f
                        },
                        new
                        {
                            ProductId = new Guid("cf07e578-f7ce-4879-b711-95939f88eac5"),
                            Name = "Refined Frozen Shirt",
                            Price = 5482.219231769770000m,
                            Quantity = 381.44608f
                        },
                        new
                        {
                            ProductId = new Guid("df263ef9-13c7-448a-8628-340a1ab0e514"),
                            Name = "Unbranded Frozen Towels",
                            Price = 4599.122926122960000m,
                            Quantity = 231.49318f
                        },
                        new
                        {
                            ProductId = new Guid("934b04d4-ee9d-4e3b-ac22-f109e9869581"),
                            Name = "Ergonomic Steel Mouse",
                            Price = 6556.19849189910000m,
                            Quantity = 108.339554f
                        },
                        new
                        {
                            ProductId = new Guid("03cd2876-5266-45e5-9771-6678ac7cee48"),
                            Name = "Intelligent Fresh Towels",
                            Price = 1755.610423260230000m,
                            Quantity = 120.461655f
                        },
                        new
                        {
                            ProductId = new Guid("50bc0b7a-0876-42c8-ad30-62b99780d158"),
                            Name = "Handcrafted Fresh Chips",
                            Price = 2598.87734306150000m,
                            Quantity = 11.997452f
                        },
                        new
                        {
                            ProductId = new Guid("d8d73bdf-f421-432d-9d9f-36eddbc92bd9"),
                            Name = "Gorgeous Plastic Pants",
                            Price = 1267.933249209990000m,
                            Quantity = 699.5111f
                        },
                        new
                        {
                            ProductId = new Guid("7eadc9eb-93b2-4f9c-afa9-6300de89220b"),
                            Name = "Incredible Cotton Shirt",
                            Price = 730.3509304580240000m,
                            Quantity = 959.0715f
                        },
                        new
                        {
                            ProductId = new Guid("c7f8d80e-1f17-45c2-b2bc-5119a6b008d5"),
                            Name = "Rustic Soft Salad",
                            Price = 7331.92354266660000m,
                            Quantity = 324.22873f
                        },
                        new
                        {
                            ProductId = new Guid("471d1f14-1f6e-41b9-8441-793362d4b146"),
                            Name = "Small Metal Shoes",
                            Price = 8413.131585984080000m,
                            Quantity = 510.38568f
                        },
                        new
                        {
                            ProductId = new Guid("ebbef47c-2372-4fa5-b188-a5a769cd9b07"),
                            Name = "Small Fresh Fish",
                            Price = 1414.538107268790000m,
                            Quantity = 204.9221f
                        },
                        new
                        {
                            ProductId = new Guid("dca87198-285e-44e4-b2fa-0e8b461e8d37"),
                            Name = "Small Concrete Ball",
                            Price = 3300.018266932810000m,
                            Quantity = 561.2882f
                        },
                        new
                        {
                            ProductId = new Guid("9b99ba87-57ec-4617-97c6-13e70e5bbdd6"),
                            Name = "Tasty Granite Mouse",
                            Price = 1090.988373584540000m,
                            Quantity = 775.49756f
                        },
                        new
                        {
                            ProductId = new Guid("f473358f-e55d-42a0-9bb4-402117c63e49"),
                            Name = "Incredible Fresh Keyboard",
                            Price = 1403.397532696120000m,
                            Quantity = 77.581635f
                        },
                        new
                        {
                            ProductId = new Guid("e4c81bf7-89be-4508-b72b-95a695d44c20"),
                            Name = "Practical Fresh Shoes",
                            Price = 6336.967483331290000m,
                            Quantity = 75.160675f
                        },
                        new
                        {
                            ProductId = new Guid("fef634b4-dd46-4c1c-b4cb-6f5e84615608"),
                            Name = "Sleek Steel Bike",
                            Price = 799.5923398033030000m,
                            Quantity = 248.24646f
                        },
                        new
                        {
                            ProductId = new Guid("b5d507eb-c485-4120-90ca-3f29f3cbb419"),
                            Name = "Fantastic Rubber Hat",
                            Price = 5088.66550033090000m,
                            Quantity = 306.8201f
                        },
                        new
                        {
                            ProductId = new Guid("9d8188a5-012b-4023-b5e0-24873b1b6fc7"),
                            Name = "Gorgeous Granite Cheese",
                            Price = 7316.988455670620000m,
                            Quantity = 498.58157f
                        },
                        new
                        {
                            ProductId = new Guid("8c380f67-c27b-43a2-9b1b-51eac3f1c424"),
                            Name = "Handmade Soft Pants",
                            Price = 8368.725206375010000m,
                            Quantity = 552.0674f
                        },
                        new
                        {
                            ProductId = new Guid("752bac75-d2e8-43f8-be4f-77d2d9967e9e"),
                            Name = "Gorgeous Frozen Mouse",
                            Price = 5935.677823315250000m,
                            Quantity = 106.81335f
                        },
                        new
                        {
                            ProductId = new Guid("bedcd76f-e04e-4926-ac12-a7bd0846f88e"),
                            Name = "Tasty Granite Bike",
                            Price = 8300.200483069320000m,
                            Quantity = 815.382f
                        },
                        new
                        {
                            ProductId = new Guid("66ca492f-b24a-4070-9bf2-ca195de0c570"),
                            Name = "Rustic Cotton Sausages",
                            Price = 2995.036135064540000m,
                            Quantity = 660.008f
                        },
                        new
                        {
                            ProductId = new Guid("1cef0c07-cd6d-4966-88bb-6b46835726a7"),
                            Name = "Sleek Steel Sausages",
                            Price = 9727.512116588920000m,
                            Quantity = 113.96786f
                        },
                        new
                        {
                            ProductId = new Guid("88ebdedc-c49c-4d84-a18d-c81c1e708e42"),
                            Name = "Fantastic Cotton Bike",
                            Price = 443.9219226908930000m,
                            Quantity = 689.8766f
                        },
                        new
                        {
                            ProductId = new Guid("8de1c672-4eb6-41eb-987f-3ef13496ecee"),
                            Name = "Ergonomic Fresh Ball",
                            Price = 4167.361103159210000m,
                            Quantity = 976.0709f
                        },
                        new
                        {
                            ProductId = new Guid("2c1a522f-454b-40f5-b1d4-92a0b7f0ab5e"),
                            Name = "Tasty Rubber Shoes",
                            Price = 4751.007084215170000m,
                            Quantity = 239.0847f
                        },
                        new
                        {
                            ProductId = new Guid("dd926ac5-5d14-4fc7-8903-b1a9c282f08f"),
                            Name = "Tasty Plastic Shirt",
                            Price = 9826.683441549920000m,
                            Quantity = 98.916794f
                        },
                        new
                        {
                            ProductId = new Guid("2a66a3ca-99ca-4333-8845-383c753edbae"),
                            Name = "Practical Metal Shirt",
                            Price = 8650.798596386770000m,
                            Quantity = 661.45654f
                        },
                        new
                        {
                            ProductId = new Guid("8cfb0875-4233-4dd5-911e-d6e596774447"),
                            Name = "Incredible Steel Shoes",
                            Price = 7700.150320721070000m,
                            Quantity = 694.65045f
                        },
                        new
                        {
                            ProductId = new Guid("17f78bb0-c2c3-4d7d-8bf9-9dc26861e122"),
                            Name = "Unbranded Steel Table",
                            Price = 2061.530558027270000m,
                            Quantity = 990.4327f
                        },
                        new
                        {
                            ProductId = new Guid("01078ea6-ccf2-4c9b-865b-67bb3007f120"),
                            Name = "Rustic Plastic Towels",
                            Price = 7438.654777242870000m,
                            Quantity = 178.8708f
                        });
                });

            modelBuilder.Entity("P03_SalesDatabase.Data.Models.Sale", b =>
                {
                    b.Property<Guid>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Customer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Product");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Store");

                    b.HasKey("SaleId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StoreId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            SaleId = new Guid("d0f095fa-dc68-4892-beb8-67765f880309"),
                            CustomerId = new Guid("5fa32538-7d44-4f21-8068-c0464bdd2ef2"),
                            Date = new DateTime(2023, 4, 15, 12, 20, 37, 167, DateTimeKind.Local).AddTicks(1793),
                            ProductId = new Guid("ebbef47c-2372-4fa5-b188-a5a769cd9b07"),
                            StoreId = new Guid("beaac625-4e29-4163-9527-443a23bb742b")
                        },
                        new
                        {
                            SaleId = new Guid("a180b693-213e-4938-9559-bf394c189eda"),
                            CustomerId = new Guid("8e7c619f-a31f-43fb-8d29-630a2eb3b52b"),
                            Date = new DateTime(2023, 4, 14, 23, 14, 31, 572, DateTimeKind.Local).AddTicks(1717),
                            ProductId = new Guid("b225ef06-9127-4caf-83e8-0c79b6a9dd9c"),
                            StoreId = new Guid("13349fec-40ce-4b17-a2db-ce2a5c1bc705")
                        },
                        new
                        {
                            SaleId = new Guid("e2070a5e-1d3d-4b94-8bdc-2b0b3ff7ab03"),
                            CustomerId = new Guid("d0589296-b3fc-487d-9a08-62134543865b"),
                            Date = new DateTime(2023, 4, 14, 17, 31, 2, 699, DateTimeKind.Local).AddTicks(9201),
                            ProductId = new Guid("03cd2876-5266-45e5-9771-6678ac7cee48"),
                            StoreId = new Guid("13349fec-40ce-4b17-a2db-ce2a5c1bc705")
                        },
                        new
                        {
                            SaleId = new Guid("96b2fc81-ce29-46a6-be2b-77a8870aa3ee"),
                            CustomerId = new Guid("e3eae361-cab6-4747-ac79-de946cd51640"),
                            Date = new DateTime(2023, 4, 15, 11, 0, 0, 836, DateTimeKind.Local).AddTicks(9033),
                            ProductId = new Guid("86ec2573-3aff-4602-88d5-27ec7ff15f28"),
                            StoreId = new Guid("a4aca96b-8726-4b51-ab77-37befb65a38f")
                        },
                        new
                        {
                            SaleId = new Guid("f08fd549-6e56-470c-9325-6718d29b7698"),
                            CustomerId = new Guid("8e7c619f-a31f-43fb-8d29-630a2eb3b52b"),
                            Date = new DateTime(2023, 4, 14, 12, 53, 45, 630, DateTimeKind.Local).AddTicks(7875),
                            ProductId = new Guid("471d1f14-1f6e-41b9-8441-793362d4b146"),
                            StoreId = new Guid("e0059e34-ada5-4d08-a92a-58a0297e27fe")
                        },
                        new
                        {
                            SaleId = new Guid("3d1c49a8-c2e9-476b-a3b6-ff00c287a0fc"),
                            CustomerId = new Guid("fe4ccf93-bf41-4100-b448-97299028dd7a"),
                            Date = new DateTime(2023, 4, 14, 16, 19, 24, 185, DateTimeKind.Local).AddTicks(9088),
                            ProductId = new Guid("7435d83b-bd82-4d34-a3c3-396ee701db9e"),
                            StoreId = new Guid("e0059e34-ada5-4d08-a92a-58a0297e27fe")
                        },
                        new
                        {
                            SaleId = new Guid("9c780ab9-c03c-4850-8cde-7c9c965e7778"),
                            CustomerId = new Guid("8e7c619f-a31f-43fb-8d29-630a2eb3b52b"),
                            Date = new DateTime(2023, 4, 15, 3, 20, 26, 818, DateTimeKind.Local).AddTicks(3807),
                            ProductId = new Guid("86ec2573-3aff-4602-88d5-27ec7ff15f28"),
                            StoreId = new Guid("e0059e34-ada5-4d08-a92a-58a0297e27fe")
                        },
                        new
                        {
                            SaleId = new Guid("79cc7737-4631-4924-b429-1b87afa1bc1c"),
                            CustomerId = new Guid("4849cfd9-69fd-404c-91ab-bccf449730d2"),
                            Date = new DateTime(2023, 4, 15, 3, 36, 28, 571, DateTimeKind.Local).AddTicks(9181),
                            ProductId = new Guid("d8d73bdf-f421-432d-9d9f-36eddbc92bd9"),
                            StoreId = new Guid("10391290-75b1-456d-9c80-343945d0c18d")
                        },
                        new
                        {
                            SaleId = new Guid("fbbf48c5-f0a6-4054-80eb-5ad4d8736162"),
                            CustomerId = new Guid("e3eae361-cab6-4747-ac79-de946cd51640"),
                            Date = new DateTime(2023, 4, 14, 16, 6, 47, 679, DateTimeKind.Local).AddTicks(3667),
                            ProductId = new Guid("86ec2573-3aff-4602-88d5-27ec7ff15f28"),
                            StoreId = new Guid("3578e5f8-5a0b-4c54-a63b-ab11e7d36fc8")
                        },
                        new
                        {
                            SaleId = new Guid("d29ac925-fe79-4143-a865-a86bce7bf3c4"),
                            CustomerId = new Guid("8e7c619f-a31f-43fb-8d29-630a2eb3b52b"),
                            Date = new DateTime(2023, 4, 15, 5, 42, 36, 455, DateTimeKind.Local).AddTicks(3737),
                            ProductId = new Guid("c7f8d80e-1f17-45c2-b2bc-5119a6b008d5"),
                            StoreId = new Guid("e0059e34-ada5-4d08-a92a-58a0297e27fe")
                        },
                        new
                        {
                            SaleId = new Guid("1e31e1fc-a8f8-42c4-ada2-e40021c9191f"),
                            CustomerId = new Guid("4849cfd9-69fd-404c-91ab-bccf449730d2"),
                            Date = new DateTime(2023, 4, 14, 18, 35, 4, 145, DateTimeKind.Local).AddTicks(4465),
                            ProductId = new Guid("b727fbcf-308c-4541-9e5f-a6a99c266137"),
                            StoreId = new Guid("e0059e34-ada5-4d08-a92a-58a0297e27fe")
                        },
                        new
                        {
                            SaleId = new Guid("b2655f95-7427-437a-99ed-e3c31cb3c33c"),
                            CustomerId = new Guid("0cb9f7a9-b855-4ed0-9ce3-b0ab6231490b"),
                            Date = new DateTime(2023, 4, 14, 22, 9, 50, 757, DateTimeKind.Local).AddTicks(4348),
                            ProductId = new Guid("b225ef06-9127-4caf-83e8-0c79b6a9dd9c"),
                            StoreId = new Guid("13349fec-40ce-4b17-a2db-ce2a5c1bc705")
                        },
                        new
                        {
                            SaleId = new Guid("e3515ec9-bfcb-4c4a-ae26-b61e4c7e2d52"),
                            CustomerId = new Guid("4849cfd9-69fd-404c-91ab-bccf449730d2"),
                            Date = new DateTime(2023, 4, 14, 21, 33, 7, 605, DateTimeKind.Local).AddTicks(6802),
                            ProductId = new Guid("390161b6-8098-486c-95ae-8fb18327acef"),
                            StoreId = new Guid("e0059e34-ada5-4d08-a92a-58a0297e27fe")
                        },
                        new
                        {
                            SaleId = new Guid("f965aa36-b664-4b2e-a9d1-5005a16789ba"),
                            CustomerId = new Guid("1d30cc86-7af1-4c30-b5c0-2a343d725a32"),
                            Date = new DateTime(2023, 4, 15, 11, 34, 36, 405, DateTimeKind.Local).AddTicks(9432),
                            ProductId = new Guid("9df986b4-e049-4092-a6de-ced84af9b186"),
                            StoreId = new Guid("134b2603-2272-47c5-8e30-77fdd2f3f7ef")
                        },
                        new
                        {
                            SaleId = new Guid("da763356-a8ba-4cc5-8a15-638404eeb512"),
                            CustomerId = new Guid("4849cfd9-69fd-404c-91ab-bccf449730d2"),
                            Date = new DateTime(2023, 4, 14, 23, 22, 51, 736, DateTimeKind.Local).AddTicks(1398),
                            ProductId = new Guid("7201abd4-8a05-428f-a18e-979acc095e61"),
                            StoreId = new Guid("13349fec-40ce-4b17-a2db-ce2a5c1bc705")
                        },
                        new
                        {
                            SaleId = new Guid("3ca6d2b5-cdf6-41d4-8585-cdedb65dc917"),
                            CustomerId = new Guid("dbcdf2a8-3bf9-45df-8f4b-312236e6d0c3"),
                            Date = new DateTime(2023, 4, 14, 20, 58, 40, 178, DateTimeKind.Local).AddTicks(9168),
                            ProductId = new Guid("b225ef06-9127-4caf-83e8-0c79b6a9dd9c"),
                            StoreId = new Guid("fb103200-2d0d-4ba7-a95c-c0a110fa0340")
                        },
                        new
                        {
                            SaleId = new Guid("dbb817c0-dd3f-4cf9-aed9-aafb72374ce3"),
                            CustomerId = new Guid("6707c0f2-2ea3-42a3-b90d-65d88e5942b4"),
                            Date = new DateTime(2023, 4, 15, 8, 15, 32, 293, DateTimeKind.Local).AddTicks(1999),
                            ProductId = new Guid("dd926ac5-5d14-4fc7-8903-b1a9c282f08f"),
                            StoreId = new Guid("3578e5f8-5a0b-4c54-a63b-ab11e7d36fc8")
                        },
                        new
                        {
                            SaleId = new Guid("cc02ab10-9e19-4209-af19-c5613aa752a5"),
                            CustomerId = new Guid("0e63364d-0fbe-4709-9a1a-afe6ac7b7028"),
                            Date = new DateTime(2023, 4, 14, 13, 57, 17, 467, DateTimeKind.Local).AddTicks(369),
                            ProductId = new Guid("b225ef06-9127-4caf-83e8-0c79b6a9dd9c"),
                            StoreId = new Guid("72177cb4-d961-47fa-b784-f310658f1b21")
                        },
                        new
                        {
                            SaleId = new Guid("72fb70df-4782-4794-ae65-b4739d4d346d"),
                            CustomerId = new Guid("dbcdf2a8-3bf9-45df-8f4b-312236e6d0c3"),
                            Date = new DateTime(2023, 4, 14, 21, 30, 47, 543, DateTimeKind.Local).AddTicks(4557),
                            ProductId = new Guid("c7f8d80e-1f17-45c2-b2bc-5119a6b008d5"),
                            StoreId = new Guid("44239b99-dc63-4b87-b9ff-964bc43ad7f2")
                        },
                        new
                        {
                            SaleId = new Guid("14db4a0b-4bcc-4c78-a606-8f9231993ffe"),
                            CustomerId = new Guid("4849cfd9-69fd-404c-91ab-bccf449730d2"),
                            Date = new DateTime(2023, 4, 15, 10, 5, 48, 766, DateTimeKind.Local).AddTicks(3087),
                            ProductId = new Guid("dd926ac5-5d14-4fc7-8903-b1a9c282f08f"),
                            StoreId = new Guid("35fd6ab9-961d-4937-9705-09579dc8be5e")
                        },
                        new
                        {
                            SaleId = new Guid("e10019c9-d676-4d27-a27a-f0c82d7e1a97"),
                            CustomerId = new Guid("e3eae361-cab6-4747-ac79-de946cd51640"),
                            Date = new DateTime(2023, 4, 15, 9, 25, 5, 637, DateTimeKind.Local).AddTicks(5583),
                            ProductId = new Guid("8c380f67-c27b-43a2-9b1b-51eac3f1c424"),
                            StoreId = new Guid("beaac625-4e29-4163-9527-443a23bb742b")
                        },
                        new
                        {
                            SaleId = new Guid("e9d32cbf-8f52-4f47-95ea-ac7083ee5ece"),
                            CustomerId = new Guid("d0589296-b3fc-487d-9a08-62134543865b"),
                            Date = new DateTime(2023, 4, 15, 6, 22, 12, 829, DateTimeKind.Local).AddTicks(5922),
                            ProductId = new Guid("fef634b4-dd46-4c1c-b4cb-6f5e84615608"),
                            StoreId = new Guid("16553225-5a91-4eef-b6b1-2529991e9da6")
                        },
                        new
                        {
                            SaleId = new Guid("1c033639-aa7c-449a-a63e-3c184f1b2c57"),
                            CustomerId = new Guid("5d71c306-bfbd-49f8-a771-c80f3df1abf2"),
                            Date = new DateTime(2023, 4, 14, 16, 17, 50, 231, DateTimeKind.Local).AddTicks(3712),
                            ProductId = new Guid("1cef0c07-cd6d-4966-88bb-6b46835726a7"),
                            StoreId = new Guid("3939e1f9-94f3-48c3-96e5-4a284211eea1")
                        },
                        new
                        {
                            SaleId = new Guid("46ead47a-a1e1-4a51-aa77-17e1c4d931c6"),
                            CustomerId = new Guid("8e7c619f-a31f-43fb-8d29-630a2eb3b52b"),
                            Date = new DateTime(2023, 4, 14, 16, 17, 57, 801, DateTimeKind.Local).AddTicks(8321),
                            ProductId = new Guid("f473358f-e55d-42a0-9bb4-402117c63e49"),
                            StoreId = new Guid("3939e1f9-94f3-48c3-96e5-4a284211eea1")
                        },
                        new
                        {
                            SaleId = new Guid("beafee79-a47f-432b-a338-99e0491548cf"),
                            CustomerId = new Guid("5d71c306-bfbd-49f8-a771-c80f3df1abf2"),
                            Date = new DateTime(2023, 4, 14, 22, 31, 27, 312, DateTimeKind.Local).AddTicks(2299),
                            ProductId = new Guid("390161b6-8098-486c-95ae-8fb18327acef"),
                            StoreId = new Guid("b4ce6892-363f-4608-93ec-87fb51d012be")
                        },
                        new
                        {
                            SaleId = new Guid("c496d4fa-df32-49d8-9286-3d9943307294"),
                            CustomerId = new Guid("80c5a775-b966-4f47-a9e4-7032dea2b047"),
                            Date = new DateTime(2023, 4, 14, 23, 34, 21, 276, DateTimeKind.Local).AddTicks(9634),
                            ProductId = new Guid("64064e0a-9ca4-4cca-bc25-d47217d6e357"),
                            StoreId = new Guid("3578e5f8-5a0b-4c54-a63b-ab11e7d36fc8")
                        },
                        new
                        {
                            SaleId = new Guid("052db8a0-0bfa-4f21-a9df-b2853d4b8476"),
                            CustomerId = new Guid("dc10c621-dd52-401d-b010-6b32572bc2ff"),
                            Date = new DateTime(2023, 4, 14, 15, 14, 57, 681, DateTimeKind.Local).AddTicks(8221),
                            ProductId = new Guid("8cfb0875-4233-4dd5-911e-d6e596774447"),
                            StoreId = new Guid("3939e1f9-94f3-48c3-96e5-4a284211eea1")
                        },
                        new
                        {
                            SaleId = new Guid("932eca28-0cc2-40f0-aaf7-c4fb33999182"),
                            CustomerId = new Guid("8c2b163a-2abc-49c6-a21a-325170f54185"),
                            Date = new DateTime(2023, 4, 14, 18, 22, 0, 638, DateTimeKind.Local).AddTicks(8443),
                            ProductId = new Guid("7eadc9eb-93b2-4f9c-afa9-6300de89220b"),
                            StoreId = new Guid("beaac625-4e29-4163-9527-443a23bb742b")
                        },
                        new
                        {
                            SaleId = new Guid("26bfe37e-2f12-4ac2-82e8-1a39a707ee2a"),
                            CustomerId = new Guid("1d30cc86-7af1-4c30-b5c0-2a343d725a32"),
                            Date = new DateTime(2023, 4, 14, 16, 31, 4, 591, DateTimeKind.Local).AddTicks(2170),
                            ProductId = new Guid("b5d507eb-c485-4120-90ca-3f29f3cbb419"),
                            StoreId = new Guid("beaac625-4e29-4163-9527-443a23bb742b")
                        },
                        new
                        {
                            SaleId = new Guid("39b0d991-49db-4325-8352-f7c19bb3ffb0"),
                            CustomerId = new Guid("0e63364d-0fbe-4709-9a1a-afe6ac7b7028"),
                            Date = new DateTime(2023, 4, 14, 13, 8, 4, 860, DateTimeKind.Local).AddTicks(9280),
                            ProductId = new Guid("a12aaaae-24ae-4695-820d-5995174630f7"),
                            StoreId = new Guid("35fd6ab9-961d-4937-9705-09579dc8be5e")
                        });
                });

            modelBuilder.Entity("P03_SalesDatabase.Data.Models.Store", b =>
                {
                    b.Property<Guid>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("StoreId");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            StoreId = new Guid("3939e1f9-94f3-48c3-96e5-4a284211eea1"),
                            Name = "Hudson - Hodkiewicz"
                        },
                        new
                        {
                            StoreId = new Guid("a4aca96b-8726-4b51-ab77-37befb65a38f"),
                            Name = "Murphy - Bartell"
                        },
                        new
                        {
                            StoreId = new Guid("e0059e34-ada5-4d08-a92a-58a0297e27fe"),
                            Name = "Terry LLC"
                        },
                        new
                        {
                            StoreId = new Guid("44239b99-dc63-4b87-b9ff-964bc43ad7f2"),
                            Name = "Conn - Bauch"
                        },
                        new
                        {
                            StoreId = new Guid("beaac625-4e29-4163-9527-443a23bb742b"),
                            Name = "Maggio, Bode and Wunsch"
                        },
                        new
                        {
                            StoreId = new Guid("5d74e877-71e6-443b-953b-50ab356f147d"),
                            Name = "Shanahan - Cole"
                        },
                        new
                        {
                            StoreId = new Guid("10391290-75b1-456d-9c80-343945d0c18d"),
                            Name = "Nolan, Gutkowski and Morissette"
                        },
                        new
                        {
                            StoreId = new Guid("13349fec-40ce-4b17-a2db-ce2a5c1bc705"),
                            Name = "Gislason, Macejkovic and Kreiger"
                        },
                        new
                        {
                            StoreId = new Guid("134b2603-2272-47c5-8e30-77fdd2f3f7ef"),
                            Name = "Gottlieb and Sons"
                        },
                        new
                        {
                            StoreId = new Guid("3578e5f8-5a0b-4c54-a63b-ab11e7d36fc8"),
                            Name = "McKenzie - Jones"
                        },
                        new
                        {
                            StoreId = new Guid("16553225-5a91-4eef-b6b1-2529991e9da6"),
                            Name = "Jacobs - Gibson"
                        },
                        new
                        {
                            StoreId = new Guid("c90d40c5-d280-4510-bebb-e924bee7bc71"),
                            Name = "Johnson Inc"
                        },
                        new
                        {
                            StoreId = new Guid("728c83bf-d917-48ba-9ed9-07beb6a52a67"),
                            Name = "Schiller and Sons"
                        },
                        new
                        {
                            StoreId = new Guid("72177cb4-d961-47fa-b784-f310658f1b21"),
                            Name = "Anderson Group"
                        },
                        new
                        {
                            StoreId = new Guid("b4ce6892-363f-4608-93ec-87fb51d012be"),
                            Name = "Sporer Inc"
                        },
                        new
                        {
                            StoreId = new Guid("35fd6ab9-961d-4937-9705-09579dc8be5e"),
                            Name = "Schultz - Walter"
                        },
                        new
                        {
                            StoreId = new Guid("fc8341df-7422-437f-9452-8b4671fc7878"),
                            Name = "Kiehn - Maggio"
                        },
                        new
                        {
                            StoreId = new Guid("425d8446-78e1-4db7-9dae-e822a16e6a78"),
                            Name = "Carroll, Schuppe and Beier"
                        },
                        new
                        {
                            StoreId = new Guid("a615e8f2-b613-4d05-9ab9-93350af90cfa"),
                            Name = "Harris, Schmitt and Schuster"
                        },
                        new
                        {
                            StoreId = new Guid("fb103200-2d0d-4ba7-a95c-c0a110fa0340"),
                            Name = "Murazik Inc"
                        });
                });

            modelBuilder.Entity("P03_SalesDatabase.Data.Models.Sale", b =>
                {
                    b.HasOne("P03_SalesDatabase.Data.Models.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P03_SalesDatabase.Data.Models.Product", "Product")
                        .WithMany("Sales")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P03_SalesDatabase.Data.Models.Store", "Store")
                        .WithMany("Sales")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("P03_SalesDatabase.Data.Models.Customer", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("P03_SalesDatabase.Data.Models.Product", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("P03_SalesDatabase.Data.Models.Store", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
