// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P03_SalesDatabase.Data;

#nullable disable

namespace P03_SalesDatabase.Migrations
{
    [DbContext(typeof(SalesContext))]
    [Migration("20230415093825_TheFirstMigration")]
    partial class TheFirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("P03_SalesDatabase.Data.Models.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreditCardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = new Guid("58885961-cd1e-4c52-9f09-1c5df88b910b"),
                            CreditCardNumber = "5893493208973103",
                            Email = "Grace_Little21@yahoo.com",
                            Name = "Grace Little"
                        },
                        new
                        {
                            CustomerId = new Guid("d8fb64be-955b-4be2-8fb1-aedd495b77a9"),
                            CreditCardNumber = "6759-7852-7709-7271",
                            Email = "Gretchen_Wintheiser@yahoo.com",
                            Name = "Gretchen Wintheiser"
                        },
                        new
                        {
                            CustomerId = new Guid("19abb28e-ece2-4d98-b182-24d8847c8d2c"),
                            CreditCardNumber = "6455-6211-4524-4228-9288",
                            Email = "Bethany_Goyette@gmail.com",
                            Name = "Bethany Goyette"
                        },
                        new
                        {
                            CustomerId = new Guid("42dc7f53-50ee-4b48-9a5e-f96cea034bb5"),
                            CreditCardNumber = "6767-7689-6161-8837-56",
                            Email = "Bridget_OConnell@hotmail.com",
                            Name = "Bridget O'Connell"
                        },
                        new
                        {
                            CustomerId = new Guid("d131eafd-86f1-4431-9048-4c6c396beb80"),
                            CreditCardNumber = "6759-9212-9379-1676",
                            Email = "Frankie9@yahoo.com",
                            Name = "Frankie Predovic"
                        },
                        new
                        {
                            CustomerId = new Guid("27ac3e41-3531-429b-968f-0e0fab929589"),
                            CreditCardNumber = "6759-4060-1890-2436",
                            Email = "Antoinette_Howe@yahoo.com",
                            Name = "Antoinette Howe"
                        },
                        new
                        {
                            CustomerId = new Guid("3ef96646-77a3-4ef5-8dd0-de6f59d54ddc"),
                            CreditCardNumber = "6517-6268-8465-9818-1926",
                            Email = "Rosa55@yahoo.com",
                            Name = "Rosa Gottlieb"
                        },
                        new
                        {
                            CustomerId = new Guid("9614297a-5810-4d1f-a4ea-5bec1972368e"),
                            CreditCardNumber = "3529-1784-8625-9948",
                            Email = "Kayla31@gmail.com",
                            Name = "Kayla Keeling"
                        },
                        new
                        {
                            CustomerId = new Guid("23b3528a-0015-4c54-80d5-5b79afebd7f9"),
                            CreditCardNumber = "6767-5042-0434-9395-860",
                            Email = "Dwayne3@gmail.com",
                            Name = "Dwayne Little"
                        },
                        new
                        {
                            CustomerId = new Guid("4894d93d-a65a-4b85-aeef-c7b292e3e4c6"),
                            CreditCardNumber = "5439-5107-9451-2028",
                            Email = "Kimberly.Jenkins69@gmail.com",
                            Name = "Kimberly Jenkins"
                        },
                        new
                        {
                            CustomerId = new Guid("872021c0-cb0b-43fe-b172-727df7e21122"),
                            CreditCardNumber = "4687346877608",
                            Email = "Belinda_Christiansen@yahoo.com",
                            Name = "Belinda Christiansen"
                        },
                        new
                        {
                            CustomerId = new Guid("c242ebe9-a273-497b-b3ed-dd7b094c6476"),
                            CreditCardNumber = "3616-423159-6737",
                            Email = "Cynthia77@yahoo.com",
                            Name = "Cynthia Hintz"
                        },
                        new
                        {
                            CustomerId = new Guid("4d305524-3ef5-4ee0-ba66-d7774344987c"),
                            CreditCardNumber = "6759-2048-2945-9963-824",
                            Email = "Jennifer_Huels73@hotmail.com",
                            Name = "Jennifer Huels"
                        },
                        new
                        {
                            CustomerId = new Guid("ad51c5e7-3685-49fe-b1d4-5554d8dc4d94"),
                            CreditCardNumber = "6767-3340-1017-5647",
                            Email = "Pablo82@gmail.com",
                            Name = "Pablo Rice"
                        },
                        new
                        {
                            CustomerId = new Guid("8dec2151-7ece-4225-9174-8daf51bae68e"),
                            CreditCardNumber = "6771-8922-4365-3254",
                            Email = "Gwen_Kulas@gmail.com",
                            Name = "Gwen Kulas"
                        },
                        new
                        {
                            CustomerId = new Guid("65d6f084-0f0c-4ba8-9ea9-4f278a3e241d"),
                            CreditCardNumber = "3656-372990-9999",
                            Email = "Brandon_OKon@hotmail.com",
                            Name = "Brandon O'Kon"
                        },
                        new
                        {
                            CustomerId = new Guid("0d159983-aeab-4a6d-909a-9830f52e0ba1"),
                            CreditCardNumber = "6304057469486062",
                            Email = "Sheryl_Stroman@yahoo.com",
                            Name = "Sheryl Stroman"
                        },
                        new
                        {
                            CustomerId = new Guid("d4f2a0d5-1567-4c93-8b0e-284dec50dfe9"),
                            CreditCardNumber = "4552-0001-0511-5475",
                            Email = "Arthur90@hotmail.com",
                            Name = "Arthur Ullrich"
                        },
                        new
                        {
                            CustomerId = new Guid("2e668adb-e696-42ae-bdbe-2abd5e17de89"),
                            CreditCardNumber = "5277-9227-5267-0430",
                            Email = "Eula_Little36@yahoo.com",
                            Name = "Eula Little"
                        },
                        new
                        {
                            CustomerId = new Guid("4bf4ded3-5c39-43af-a1b1-f58f1479b3dd"),
                            CreditCardNumber = "6398-3249-9743-7711",
                            Email = "Stephen_Larson43@hotmail.com",
                            Name = "Stephen Larson"
                        });
                });

            modelBuilder.Entity("P03_SalesDatabase.Data.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("fc6a8d35-83df-445e-9337-bbc706c2ed73"),
                            Name = "Intelligent Steel Table",
                            Price = 1152.746683051960000m,
                            Quantity = 838.27155f
                        },
                        new
                        {
                            ProductId = new Guid("029f71c6-2326-48d6-b347-2d86ef77e587"),
                            Name = "Rustic Wooden Chips",
                            Price = 1621.482410613320000m,
                            Quantity = 767.5265f
                        },
                        new
                        {
                            ProductId = new Guid("b164503e-dcda-49e5-8042-7448af54e6e4"),
                            Name = "Refined Plastic Sausages",
                            Price = 2121.550174376840000m,
                            Quantity = 981.68463f
                        },
                        new
                        {
                            ProductId = new Guid("31bbb11e-571d-4eca-a069-b7ceba8bcb97"),
                            Name = "Refined Granite Bacon",
                            Price = 3158.254351134870000m,
                            Quantity = 322.5808f
                        },
                        new
                        {
                            ProductId = new Guid("dd317f36-fba7-47bb-a907-7c2f8e5bc983"),
                            Name = "Rustic Wooden Shirt",
                            Price = 5111.537396702140000m,
                            Quantity = 133.55197f
                        },
                        new
                        {
                            ProductId = new Guid("bcbaef2a-dd26-4ec7-92c1-0c52d66653de"),
                            Name = "Handmade Concrete Fish",
                            Price = 7216.693885902250000m,
                            Quantity = 79.336205f
                        },
                        new
                        {
                            ProductId = new Guid("9ad63002-9d2b-4f77-94a2-5a47c0ef689b"),
                            Name = "Tasty Fresh Pants",
                            Price = 5850.852265975140000m,
                            Quantity = 124.93374f
                        },
                        new
                        {
                            ProductId = new Guid("dae1a5a6-881f-48eb-a066-9a455b4ae7f3"),
                            Name = "Fantastic Plastic Ball",
                            Price = 6480.190793703990000m,
                            Quantity = 335.39667f
                        },
                        new
                        {
                            ProductId = new Guid("612f0ef7-656a-4897-8bce-ba738132c839"),
                            Name = "Licensed Steel Salad",
                            Price = 4825.05801923360000m,
                            Quantity = 90.76204f
                        },
                        new
                        {
                            ProductId = new Guid("b1ab6962-f308-48e8-8bca-d162b21ec013"),
                            Name = "Licensed Plastic Shirt",
                            Price = 3429.506784251510000m,
                            Quantity = 443.38495f
                        },
                        new
                        {
                            ProductId = new Guid("46dfb232-6235-485c-8da9-b60e5e15ba32"),
                            Name = "Tasty Soft Cheese",
                            Price = 3908.856826725360000m,
                            Quantity = 706.5572f
                        },
                        new
                        {
                            ProductId = new Guid("ed639751-bd69-4712-92f4-728b1b89c173"),
                            Name = "Sleek Fresh Soap",
                            Price = 2067.226209220540000m,
                            Quantity = 228.39719f
                        },
                        new
                        {
                            ProductId = new Guid("b0a5f1fb-5bcf-4426-b0e3-cc3e3faed721"),
                            Name = "Refined Concrete Ball",
                            Price = 3667.332299884210000m,
                            Quantity = 713.10504f
                        },
                        new
                        {
                            ProductId = new Guid("611c9e00-7d77-40e9-a355-2c3a45503183"),
                            Name = "Unbranded Metal Hat",
                            Price = 388.1598717012320000m,
                            Quantity = 210.35046f
                        },
                        new
                        {
                            ProductId = new Guid("2dd328a0-4b2f-409e-a824-c484574a3d97"),
                            Name = "Small Metal Keyboard",
                            Price = 9484.872626590220000m,
                            Quantity = 219.79092f
                        },
                        new
                        {
                            ProductId = new Guid("659015bb-49c5-4f54-967a-143d162b1d95"),
                            Name = "Incredible Granite Bike",
                            Price = 7786.876306506380000m,
                            Quantity = 488.67523f
                        },
                        new
                        {
                            ProductId = new Guid("dd084c63-b776-4cd2-b85e-e2cec6b5746a"),
                            Name = "Refined Granite Hat",
                            Price = 8032.861146316770000m,
                            Quantity = 803.93756f
                        },
                        new
                        {
                            ProductId = new Guid("b35364b5-955a-481f-927a-3934ebde2bea"),
                            Name = "Fantastic Metal Towels",
                            Price = 8849.414553623220000m,
                            Quantity = 239.26434f
                        },
                        new
                        {
                            ProductId = new Guid("3d343dd4-0007-4c8e-8d96-3d8be854c2e1"),
                            Name = "Handcrafted Soft Soap",
                            Price = 9526.72220896720000m,
                            Quantity = 217.20303f
                        },
                        new
                        {
                            ProductId = new Guid("e41382ab-19a4-4cd0-8cde-621dde807841"),
                            Name = "Small Rubber Ball",
                            Price = 8577.198799551260000m,
                            Quantity = 54.459644f
                        },
                        new
                        {
                            ProductId = new Guid("f0df89a4-948f-4a2c-94ad-a098e1775dd7"),
                            Name = "Incredible Concrete Fish",
                            Price = 4506.259764260430000m,
                            Quantity = 905.6777f
                        },
                        new
                        {
                            ProductId = new Guid("5fbdd46b-d0b5-4543-a301-559052b522ed"),
                            Name = "Ergonomic Rubber Table",
                            Price = 1648.552782453260000m,
                            Quantity = 796.50446f
                        },
                        new
                        {
                            ProductId = new Guid("922b39a9-86f7-4d65-9321-8da357e3a1f0"),
                            Name = "Refined Granite Tuna",
                            Price = 8109.401960883150000m,
                            Quantity = 32.95414f
                        },
                        new
                        {
                            ProductId = new Guid("8964f3c3-9a27-4daf-9334-dd44e40cb90f"),
                            Name = "Handcrafted Fresh Car",
                            Price = 5076.904433578580000m,
                            Quantity = 617.551f
                        },
                        new
                        {
                            ProductId = new Guid("a8364632-afe2-4d4f-b4d8-c9693df5efb9"),
                            Name = "Awesome Plastic Fish",
                            Price = 1394.485361085930000m,
                            Quantity = 406.9684f
                        },
                        new
                        {
                            ProductId = new Guid("7e0afba3-6f83-48a3-a79a-f7b2e7122b49"),
                            Name = "Ergonomic Metal Sausages",
                            Price = 1577.903452402670000m,
                            Quantity = 516.7398f
                        },
                        new
                        {
                            ProductId = new Guid("e548160d-fbc1-4bcf-a12c-c6336c278f26"),
                            Name = "Incredible Fresh Gloves",
                            Price = 5831.881117764180000m,
                            Quantity = 668.5122f
                        },
                        new
                        {
                            ProductId = new Guid("cb76051d-84e5-46f3-a230-2cd0d5f30d77"),
                            Name = "Incredible Rubber Table",
                            Price = 610.8750622197640000m,
                            Quantity = 587.98785f
                        },
                        new
                        {
                            ProductId = new Guid("62768908-6ea3-40f6-83e7-e406a54de05a"),
                            Name = "Licensed Wooden Salad",
                            Price = 861.2870482604370000m,
                            Quantity = 480.02393f
                        },
                        new
                        {
                            ProductId = new Guid("1095f0b1-cce8-423a-af19-c4cdf8c19158"),
                            Name = "Practical Cotton Ball",
                            Price = 4056.786719411570000m,
                            Quantity = 207.38115f
                        },
                        new
                        {
                            ProductId = new Guid("f8032cd1-85de-40eb-aa27-771f4deb4e81"),
                            Name = "Practical Rubber Ball",
                            Price = 3811.141164034160000m,
                            Quantity = 603.86896f
                        },
                        new
                        {
                            ProductId = new Guid("1dc01f2c-b787-4ef7-85f5-b9f5ebd65873"),
                            Name = "Handcrafted Wooden Cheese",
                            Price = 7300.583579649210000m,
                            Quantity = 36.808407f
                        },
                        new
                        {
                            ProductId = new Guid("ec99b2e6-bec1-4dbe-90f2-3e6828e4d93c"),
                            Name = "Ergonomic Plastic Gloves",
                            Price = 7899.0661737820000m,
                            Quantity = 8.763154f
                        },
                        new
                        {
                            ProductId = new Guid("9102fead-d434-4f69-9eab-838178697967"),
                            Name = "Small Plastic Salad",
                            Price = 5700.399263022840000m,
                            Quantity = 742.5623f
                        },
                        new
                        {
                            ProductId = new Guid("6d9f3674-2a4e-4b61-8ba2-2395482a8397"),
                            Name = "Sleek Granite Soap",
                            Price = 8558.768673436720000m,
                            Quantity = 831.1672f
                        },
                        new
                        {
                            ProductId = new Guid("d9dc11b2-84c2-4ea1-8a14-5347075826c8"),
                            Name = "Small Cotton Sausages",
                            Price = 7400.263131107660000m,
                            Quantity = 372.72357f
                        },
                        new
                        {
                            ProductId = new Guid("463940e4-d568-412f-8fbe-af0affab79a5"),
                            Name = "Gorgeous Plastic Chips",
                            Price = 9346.079260292050000m,
                            Quantity = 844.5623f
                        },
                        new
                        {
                            ProductId = new Guid("83742aae-610d-4f61-a5d5-7e2f66d2e73a"),
                            Name = "Tasty Cotton Salad",
                            Price = 6924.630668633160000m,
                            Quantity = 581.1025f
                        },
                        new
                        {
                            ProductId = new Guid("06657346-12d2-4638-a023-e75e1f6b3354"),
                            Name = "Handmade Frozen Bike",
                            Price = 4913.852609162340000m,
                            Quantity = 72.91686f
                        },
                        new
                        {
                            ProductId = new Guid("37eafcab-a577-4426-8915-e176a860aead"),
                            Name = "Awesome Fresh Bacon",
                            Price = 2143.435636521510000m,
                            Quantity = 96.70534f
                        });
                });

            modelBuilder.Entity("P03_SalesDatabase.Data.Models.Sale", b =>
                {
                    b.Property<Guid>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Customer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Product");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Store");

                    b.HasKey("SaleId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StoreId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            SaleId = new Guid("009822ce-03c9-4bd6-9c52-29c714919020"),
                            CustomerId = new Guid("d8fb64be-955b-4be2-8fb1-aedd495b77a9"),
                            Date = new DateTime(2023, 4, 15, 5, 1, 40, 377, DateTimeKind.Local).AddTicks(607),
                            ProductId = new Guid("31bbb11e-571d-4eca-a069-b7ceba8bcb97"),
                            StoreId = new Guid("6db9ce7c-287d-474b-9ee4-58558a53e8b8")
                        },
                        new
                        {
                            SaleId = new Guid("21098cb4-74ba-4b57-9cbe-3116849c59e1"),
                            CustomerId = new Guid("27ac3e41-3531-429b-968f-0e0fab929589"),
                            Date = new DateTime(2023, 4, 14, 21, 1, 16, 121, DateTimeKind.Local).AddTicks(7332),
                            ProductId = new Guid("31bbb11e-571d-4eca-a069-b7ceba8bcb97"),
                            StoreId = new Guid("6db9ce7c-287d-474b-9ee4-58558a53e8b8")
                        },
                        new
                        {
                            SaleId = new Guid("d77b4ef1-e6a7-46f5-a268-27000f143a22"),
                            CustomerId = new Guid("d131eafd-86f1-4431-9048-4c6c396beb80"),
                            Date = new DateTime(2023, 4, 14, 21, 45, 16, 854, DateTimeKind.Local).AddTicks(9256),
                            ProductId = new Guid("b1ab6962-f308-48e8-8bca-d162b21ec013"),
                            StoreId = new Guid("3ce5bfde-5c84-45aa-b77b-ff8fd39c0976")
                        },
                        new
                        {
                            SaleId = new Guid("b6a741e6-cd3c-4c84-b4c6-f3cd7946df7a"),
                            CustomerId = new Guid("23b3528a-0015-4c54-80d5-5b79afebd7f9"),
                            Date = new DateTime(2023, 4, 15, 1, 20, 38, 807, DateTimeKind.Local).AddTicks(7328),
                            ProductId = new Guid("b164503e-dcda-49e5-8042-7448af54e6e4"),
                            StoreId = new Guid("eaeb01c4-9e06-492b-951b-b67f96d7e6f2")
                        },
                        new
                        {
                            SaleId = new Guid("f32a2c5a-542d-43d5-b4be-cc4203782d75"),
                            CustomerId = new Guid("27ac3e41-3531-429b-968f-0e0fab929589"),
                            Date = new DateTime(2023, 4, 14, 15, 8, 35, 932, DateTimeKind.Local).AddTicks(1269),
                            ProductId = new Guid("bcbaef2a-dd26-4ec7-92c1-0c52d66653de"),
                            StoreId = new Guid("fdda4973-d2aa-4df6-a686-594e85d36833")
                        },
                        new
                        {
                            SaleId = new Guid("5dc62535-ac54-49d8-9689-3be0a71ae30f"),
                            CustomerId = new Guid("23b3528a-0015-4c54-80d5-5b79afebd7f9"),
                            Date = new DateTime(2023, 4, 15, 10, 23, 9, 148, DateTimeKind.Local).AddTicks(7059),
                            ProductId = new Guid("3d343dd4-0007-4c8e-8d96-3d8be854c2e1"),
                            StoreId = new Guid("90c782bd-902a-4764-a6ad-83f2581e9f32")
                        },
                        new
                        {
                            SaleId = new Guid("dec42efe-5f20-43b4-b480-34f113b70e8a"),
                            CustomerId = new Guid("23b3528a-0015-4c54-80d5-5b79afebd7f9"),
                            Date = new DateTime(2023, 4, 14, 15, 47, 45, 138, DateTimeKind.Local).AddTicks(5340),
                            ProductId = new Guid("e41382ab-19a4-4cd0-8cde-621dde807841"),
                            StoreId = new Guid("f8954168-7941-488a-a641-d3eb704dbfe9")
                        },
                        new
                        {
                            SaleId = new Guid("9905131f-9f50-4e6b-a7e6-a921fd9ae242"),
                            CustomerId = new Guid("4894d93d-a65a-4b85-aeef-c7b292e3e4c6"),
                            Date = new DateTime(2023, 4, 14, 19, 47, 12, 875, DateTimeKind.Local).AddTicks(2440),
                            ProductId = new Guid("b1ab6962-f308-48e8-8bca-d162b21ec013"),
                            StoreId = new Guid("6db9ce7c-287d-474b-9ee4-58558a53e8b8")
                        },
                        new
                        {
                            SaleId = new Guid("5f0213a0-2537-4d57-836d-974cbb2d6dcc"),
                            CustomerId = new Guid("d8fb64be-955b-4be2-8fb1-aedd495b77a9"),
                            Date = new DateTime(2023, 4, 15, 8, 16, 27, 180, DateTimeKind.Local).AddTicks(841),
                            ProductId = new Guid("46dfb232-6235-485c-8da9-b60e5e15ba32"),
                            StoreId = new Guid("90c782bd-902a-4764-a6ad-83f2581e9f32")
                        },
                        new
                        {
                            SaleId = new Guid("84fecc35-db2d-4b51-afe8-8c0c327a9af1"),
                            CustomerId = new Guid("58885961-cd1e-4c52-9f09-1c5df88b910b"),
                            Date = new DateTime(2023, 4, 15, 1, 16, 45, 848, DateTimeKind.Local).AddTicks(6153),
                            ProductId = new Guid("b1ab6962-f308-48e8-8bca-d162b21ec013"),
                            StoreId = new Guid("fdda4973-d2aa-4df6-a686-594e85d36833")
                        },
                        new
                        {
                            SaleId = new Guid("bcf7df0e-51d7-4498-963b-bdfa4f09c533"),
                            CustomerId = new Guid("4894d93d-a65a-4b85-aeef-c7b292e3e4c6"),
                            Date = new DateTime(2023, 4, 15, 6, 56, 43, 19, DateTimeKind.Local).AddTicks(8605),
                            ProductId = new Guid("46dfb232-6235-485c-8da9-b60e5e15ba32"),
                            StoreId = new Guid("6db9ce7c-287d-474b-9ee4-58558a53e8b8")
                        },
                        new
                        {
                            SaleId = new Guid("2b73fd6a-a64b-4539-9710-e8de5ce8d51c"),
                            CustomerId = new Guid("d131eafd-86f1-4431-9048-4c6c396beb80"),
                            Date = new DateTime(2023, 4, 15, 10, 2, 14, 953, DateTimeKind.Local).AddTicks(7474),
                            ProductId = new Guid("ed639751-bd69-4712-92f4-728b1b89c173"),
                            StoreId = new Guid("eaeb01c4-9e06-492b-951b-b67f96d7e6f2")
                        },
                        new
                        {
                            SaleId = new Guid("2318dc5d-59af-4756-85bf-9bc2ec8a288e"),
                            CustomerId = new Guid("4894d93d-a65a-4b85-aeef-c7b292e3e4c6"),
                            Date = new DateTime(2023, 4, 15, 9, 12, 57, 261, DateTimeKind.Local).AddTicks(4245),
                            ProductId = new Guid("dd317f36-fba7-47bb-a907-7c2f8e5bc983"),
                            StoreId = new Guid("1b85455f-b827-42e6-855c-36cad3e88a3e")
                        },
                        new
                        {
                            SaleId = new Guid("4f134c39-3efa-44b8-9609-e2f6fc772f32"),
                            CustomerId = new Guid("23b3528a-0015-4c54-80d5-5b79afebd7f9"),
                            Date = new DateTime(2023, 4, 14, 17, 13, 9, 611, DateTimeKind.Local).AddTicks(552),
                            ProductId = new Guid("659015bb-49c5-4f54-967a-143d162b1d95"),
                            StoreId = new Guid("6f1a1738-e6ad-4d29-afdc-952edd10ac36")
                        },
                        new
                        {
                            SaleId = new Guid("5f37e354-136e-4e15-93f1-7520233f6409"),
                            CustomerId = new Guid("4894d93d-a65a-4b85-aeef-c7b292e3e4c6"),
                            Date = new DateTime(2023, 4, 15, 9, 41, 45, 302, DateTimeKind.Local).AddTicks(1706),
                            ProductId = new Guid("b35364b5-955a-481f-927a-3934ebde2bea"),
                            StoreId = new Guid("f8954168-7941-488a-a641-d3eb704dbfe9")
                        },
                        new
                        {
                            SaleId = new Guid("9efcc970-8b93-4c5c-affd-def7d852d3bb"),
                            CustomerId = new Guid("9614297a-5810-4d1f-a4ea-5bec1972368e"),
                            Date = new DateTime(2023, 4, 15, 3, 52, 29, 912, DateTimeKind.Local).AddTicks(2789),
                            ProductId = new Guid("463940e4-d568-412f-8fbe-af0affab79a5"),
                            StoreId = new Guid("521ba706-10a4-433c-9df2-a68f050afa00")
                        },
                        new
                        {
                            SaleId = new Guid("15ca4e81-0b68-4820-aab6-1f752ad58344"),
                            CustomerId = new Guid("27ac3e41-3531-429b-968f-0e0fab929589"),
                            Date = new DateTime(2023, 4, 15, 4, 24, 17, 591, DateTimeKind.Local).AddTicks(2580),
                            ProductId = new Guid("1dc01f2c-b787-4ef7-85f5-b9f5ebd65873"),
                            StoreId = new Guid("6f1a1738-e6ad-4d29-afdc-952edd10ac36")
                        },
                        new
                        {
                            SaleId = new Guid("6758f564-1645-48c7-880c-368815f2ff6d"),
                            CustomerId = new Guid("d8fb64be-955b-4be2-8fb1-aedd495b77a9"),
                            Date = new DateTime(2023, 4, 14, 20, 29, 10, 96, DateTimeKind.Local).AddTicks(9644),
                            ProductId = new Guid("659015bb-49c5-4f54-967a-143d162b1d95"),
                            StoreId = new Guid("a3569e74-209c-4b28-83b4-2219cec7da22")
                        },
                        new
                        {
                            SaleId = new Guid("bf372875-ac7d-49a9-a5b7-2fa6455cc5fa"),
                            CustomerId = new Guid("9614297a-5810-4d1f-a4ea-5bec1972368e"),
                            Date = new DateTime(2023, 4, 15, 5, 40, 41, 153, DateTimeKind.Local).AddTicks(996),
                            ProductId = new Guid("463940e4-d568-412f-8fbe-af0affab79a5"),
                            StoreId = new Guid("fdda4973-d2aa-4df6-a686-594e85d36833")
                        },
                        new
                        {
                            SaleId = new Guid("f244e454-9461-41c2-b763-e5ad21d39bb3"),
                            CustomerId = new Guid("42dc7f53-50ee-4b48-9a5e-f96cea034bb5"),
                            Date = new DateTime(2023, 4, 15, 1, 44, 42, 35, DateTimeKind.Local).AddTicks(880),
                            ProductId = new Guid("b164503e-dcda-49e5-8042-7448af54e6e4"),
                            StoreId = new Guid("8893c552-d404-45bc-8b56-7a50017cf5ac")
                        },
                        new
                        {
                            SaleId = new Guid("561edde2-eacd-48a6-8aea-56ab31c2bbda"),
                            CustomerId = new Guid("2e668adb-e696-42ae-bdbe-2abd5e17de89"),
                            Date = new DateTime(2023, 4, 15, 10, 4, 21, 377, DateTimeKind.Local).AddTicks(7709),
                            ProductId = new Guid("62768908-6ea3-40f6-83e7-e406a54de05a"),
                            StoreId = new Guid("eaeb01c4-9e06-492b-951b-b67f96d7e6f2")
                        },
                        new
                        {
                            SaleId = new Guid("17482f29-a62c-4211-9587-8ae30efb4f20"),
                            CustomerId = new Guid("65d6f084-0f0c-4ba8-9ea9-4f278a3e241d"),
                            Date = new DateTime(2023, 4, 14, 15, 21, 1, 392, DateTimeKind.Local).AddTicks(846),
                            ProductId = new Guid("cb76051d-84e5-46f3-a230-2cd0d5f30d77"),
                            StoreId = new Guid("5746c411-8c51-412a-93d4-73a11f5dca93")
                        },
                        new
                        {
                            SaleId = new Guid("51874478-8544-4c97-b03a-599e0b75151d"),
                            CustomerId = new Guid("872021c0-cb0b-43fe-b172-727df7e21122"),
                            Date = new DateTime(2023, 4, 15, 10, 47, 13, 365, DateTimeKind.Local).AddTicks(4935),
                            ProductId = new Guid("6d9f3674-2a4e-4b61-8ba2-2395482a8397"),
                            StoreId = new Guid("3ce5bfde-5c84-45aa-b77b-ff8fd39c0976")
                        },
                        new
                        {
                            SaleId = new Guid("174f7cd0-da8e-43c7-b54f-f0b9892f500b"),
                            CustomerId = new Guid("9614297a-5810-4d1f-a4ea-5bec1972368e"),
                            Date = new DateTime(2023, 4, 14, 15, 51, 35, 781, DateTimeKind.Local).AddTicks(5454),
                            ProductId = new Guid("a8364632-afe2-4d4f-b4d8-c9693df5efb9"),
                            StoreId = new Guid("d77a3211-15ac-4f1f-be71-6323872f5954")
                        },
                        new
                        {
                            SaleId = new Guid("c217d137-778b-49b9-bb13-88ad3b1f53f7"),
                            CustomerId = new Guid("27ac3e41-3531-429b-968f-0e0fab929589"),
                            Date = new DateTime(2023, 4, 15, 10, 14, 30, 577, DateTimeKind.Local).AddTicks(2044),
                            ProductId = new Guid("ec99b2e6-bec1-4dbe-90f2-3e6828e4d93c"),
                            StoreId = new Guid("42245df4-d04c-46f0-8938-6af7b6ccdb38")
                        },
                        new
                        {
                            SaleId = new Guid("55e4f49e-d405-46c9-80c5-76c97ad64c8a"),
                            CustomerId = new Guid("23b3528a-0015-4c54-80d5-5b79afebd7f9"),
                            Date = new DateTime(2023, 4, 14, 14, 44, 5, 394, DateTimeKind.Local).AddTicks(1113),
                            ProductId = new Guid("5fbdd46b-d0b5-4543-a301-559052b522ed"),
                            StoreId = new Guid("f8954168-7941-488a-a641-d3eb704dbfe9")
                        },
                        new
                        {
                            SaleId = new Guid("3fca3502-b9b8-4be2-a1f8-bcecde79ee6f"),
                            CustomerId = new Guid("42dc7f53-50ee-4b48-9a5e-f96cea034bb5"),
                            Date = new DateTime(2023, 4, 15, 12, 3, 39, 749, DateTimeKind.Local).AddTicks(4914),
                            ProductId = new Guid("029f71c6-2326-48d6-b347-2d86ef77e587"),
                            StoreId = new Guid("896163a6-2134-4104-9b48-6442254f18bc")
                        },
                        new
                        {
                            SaleId = new Guid("16ac77b5-a90a-4f59-a49c-81c9dd28b73f"),
                            CustomerId = new Guid("d131eafd-86f1-4431-9048-4c6c396beb80"),
                            Date = new DateTime(2023, 4, 14, 13, 4, 56, 348, DateTimeKind.Local).AddTicks(3925),
                            ProductId = new Guid("6d9f3674-2a4e-4b61-8ba2-2395482a8397"),
                            StoreId = new Guid("fdda4973-d2aa-4df6-a686-594e85d36833")
                        },
                        new
                        {
                            SaleId = new Guid("13fd42b5-1ddb-4f14-9163-eda9aadc4638"),
                            CustomerId = new Guid("58885961-cd1e-4c52-9f09-1c5df88b910b"),
                            Date = new DateTime(2023, 4, 15, 4, 28, 31, 284, DateTimeKind.Local).AddTicks(9444),
                            ProductId = new Guid("463940e4-d568-412f-8fbe-af0affab79a5"),
                            StoreId = new Guid("73353e38-62c4-4293-aeec-02eb2652b98c")
                        },
                        new
                        {
                            SaleId = new Guid("f2155623-e6ef-4648-bbbc-091c5cc43f8e"),
                            CustomerId = new Guid("872021c0-cb0b-43fe-b172-727df7e21122"),
                            Date = new DateTime(2023, 4, 14, 14, 38, 46, 983, DateTimeKind.Local).AddTicks(5936),
                            ProductId = new Guid("37eafcab-a577-4426-8915-e176a860aead"),
                            StoreId = new Guid("6f1a1738-e6ad-4d29-afdc-952edd10ac36")
                        });
                });

            modelBuilder.Entity("P03_SalesDatabase.Data.Models.Store", b =>
                {
                    b.Property<Guid>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("StoreId");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            StoreId = new Guid("6db9ce7c-287d-474b-9ee4-58558a53e8b8"),
                            Name = "Simonis Inc"
                        },
                        new
                        {
                            StoreId = new Guid("1b85455f-b827-42e6-855c-36cad3e88a3e"),
                            Name = "Cummerata - Marvin"
                        },
                        new
                        {
                            StoreId = new Guid("3ce5bfde-5c84-45aa-b77b-ff8fd39c0976"),
                            Name = "Kreiger, Wehner and Leuschke"
                        },
                        new
                        {
                            StoreId = new Guid("fdda4973-d2aa-4df6-a686-594e85d36833"),
                            Name = "Donnelly, Lindgren and Grimes"
                        },
                        new
                        {
                            StoreId = new Guid("6f1a1738-e6ad-4d29-afdc-952edd10ac36"),
                            Name = "Cruickshank Inc"
                        },
                        new
                        {
                            StoreId = new Guid("f8954168-7941-488a-a641-d3eb704dbfe9"),
                            Name = "Smith - Koepp"
                        },
                        new
                        {
                            StoreId = new Guid("6a4eeabf-c150-449f-8a1b-5c8c01e74837"),
                            Name = "Jaskolski and Sons"
                        },
                        new
                        {
                            StoreId = new Guid("eaeb01c4-9e06-492b-951b-b67f96d7e6f2"),
                            Name = "Hagenes Inc"
                        },
                        new
                        {
                            StoreId = new Guid("90c782bd-902a-4764-a6ad-83f2581e9f32"),
                            Name = "Weber - Miller"
                        },
                        new
                        {
                            StoreId = new Guid("521ba706-10a4-433c-9df2-a68f050afa00"),
                            Name = "Pacocha LLC"
                        },
                        new
                        {
                            StoreId = new Guid("5746c411-8c51-412a-93d4-73a11f5dca93"),
                            Name = "Hamill - Quigley"
                        },
                        new
                        {
                            StoreId = new Guid("896163a6-2134-4104-9b48-6442254f18bc"),
                            Name = "Pfannerstill and Sons"
                        },
                        new
                        {
                            StoreId = new Guid("42245df4-d04c-46f0-8938-6af7b6ccdb38"),
                            Name = "Ferry Inc"
                        },
                        new
                        {
                            StoreId = new Guid("73353e38-62c4-4293-aeec-02eb2652b98c"),
                            Name = "Konopelski and Sons"
                        },
                        new
                        {
                            StoreId = new Guid("8893c552-d404-45bc-8b56-7a50017cf5ac"),
                            Name = "Boyle, Balistreri and Collier"
                        },
                        new
                        {
                            StoreId = new Guid("9b752c22-78ec-4c3c-a013-bae2434ec147"),
                            Name = "Waters, Halvorson and McCullough"
                        },
                        new
                        {
                            StoreId = new Guid("1737871e-8487-43f7-b676-d9dd13c53b9a"),
                            Name = "Grady Group"
                        },
                        new
                        {
                            StoreId = new Guid("a3569e74-209c-4b28-83b4-2219cec7da22"),
                            Name = "Robel, Pollich and Legros"
                        },
                        new
                        {
                            StoreId = new Guid("d77a3211-15ac-4f1f-be71-6323872f5954"),
                            Name = "Nitzsche - Lubowitz"
                        },
                        new
                        {
                            StoreId = new Guid("cf871379-e6bf-4c19-b100-d2dbffe4f28e"),
                            Name = "Gaylord - Kub"
                        });
                });

            modelBuilder.Entity("P03_SalesDatabase.Data.Models.Sale", b =>
                {
                    b.HasOne("P03_SalesDatabase.Data.Models.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P03_SalesDatabase.Data.Models.Product", "Product")
                        .WithMany("Sales")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P03_SalesDatabase.Data.Models.Store", "Store")
                        .WithMany("Sales")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("P03_SalesDatabase.Data.Models.Customer", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("P03_SalesDatabase.Data.Models.Product", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("P03_SalesDatabase.Data.Models.Store", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
