// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P03_SalesDatabase.Data;

#nullable disable

namespace P03_SalesDatabase.Migrations
{
    [DbContext(typeof(SalesContext))]
    [Migration("20230415095330_SalesAddDateDefault")]
    partial class SalesAddDateDefault
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("P03_SalesDatabase.Data.Models.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreditCardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = new Guid("2585d500-f84c-42ad-91f5-aabc7a001160"),
                            CreditCardNumber = "6759-3486-5625-9317",
                            Email = "Tamara13@gmail.com",
                            Name = "Tamara Will"
                        },
                        new
                        {
                            CustomerId = new Guid("95faa7e8-4fac-46f2-9642-2809bb52fbf3"),
                            CreditCardNumber = "6011-7444-0625-1139",
                            Email = "Nicole_Rohan@hotmail.com",
                            Name = "Nicole Rohan"
                        },
                        new
                        {
                            CustomerId = new Guid("bdc0d062-d405-4b30-8a88-982c8cd810b0"),
                            CreditCardNumber = "3528-2555-5302-3083",
                            Email = "Dianne_Kiehn@yahoo.com",
                            Name = "Dianne Kiehn"
                        },
                        new
                        {
                            CustomerId = new Guid("cb583612-f843-4997-8f4f-1ea30345a571"),
                            CreditCardNumber = "3559-8327-1322-0676",
                            Email = "Ramona69@yahoo.com",
                            Name = "Ramona Hackett"
                        },
                        new
                        {
                            CustomerId = new Guid("76357a45-a4c8-44ad-8cf2-3b4aae0a7fa5"),
                            CreditCardNumber = "6380-9531-4560-0372",
                            Email = "Adrienne_Cronin78@hotmail.com",
                            Name = "Adrienne Cronin"
                        },
                        new
                        {
                            CustomerId = new Guid("8d8bdf71-2da2-4ad1-a834-301a32bfa72f"),
                            CreditCardNumber = "3051-911727-4376",
                            Email = "Horace85@gmail.com",
                            Name = "Horace Stamm"
                        },
                        new
                        {
                            CustomerId = new Guid("ab938cad-6465-4026-9ef3-3d9b30e20af9"),
                            CreditCardNumber = "6304604817785479",
                            Email = "Chester_Swaniawski62@yahoo.com",
                            Name = "Chester Swaniawski"
                        },
                        new
                        {
                            CustomerId = new Guid("696c34e8-9b3d-4d9e-b060-44f6f0869acf"),
                            CreditCardNumber = "6393-7970-6668-4344",
                            Email = "Blanche.Mertz@hotmail.com",
                            Name = "Blanche Mertz"
                        },
                        new
                        {
                            CustomerId = new Guid("2f350e0f-1e05-489e-a534-d3dbccb4a549"),
                            CreditCardNumber = "3539-0096-4434-5170",
                            Email = "Douglas29@yahoo.com",
                            Name = "Douglas Watsica"
                        },
                        new
                        {
                            CustomerId = new Guid("221fde44-da7e-40a4-a8b6-b4453d968064"),
                            CreditCardNumber = "5020-4765-0771-5297",
                            Email = "Jan_Monahan@hotmail.com",
                            Name = "Jan Monahan"
                        },
                        new
                        {
                            CustomerId = new Guid("17833e28-fa62-44e9-af89-02115ce53ed6"),
                            CreditCardNumber = "3528-7940-1903-2684",
                            Email = "Paul_Keebler5@yahoo.com",
                            Name = "Paul Keebler"
                        },
                        new
                        {
                            CustomerId = new Guid("16aeae9f-824e-470b-ab86-109913afa19f"),
                            CreditCardNumber = "67599561053505431438",
                            Email = "Rebecca27@gmail.com",
                            Name = "Rebecca Schumm"
                        },
                        new
                        {
                            CustomerId = new Guid("da6ea412-8e15-4056-9920-c9c278f7592d"),
                            CreditCardNumber = "3015-062940-5199",
                            Email = "Kayla.Jaskolski@gmail.com",
                            Name = "Kayla Jaskolski"
                        },
                        new
                        {
                            CustomerId = new Guid("009762af-d785-452f-b238-5b19054b80bc"),
                            CreditCardNumber = "6759556054981411",
                            Email = "Kristine61@hotmail.com",
                            Name = "Kristine Schuster"
                        },
                        new
                        {
                            CustomerId = new Guid("1877b944-abc2-4520-b8f3-2e7882abb42f"),
                            CreditCardNumber = "6761-2574-9607-4040",
                            Email = "Erik64@gmail.com",
                            Name = "Erik Ondricka"
                        },
                        new
                        {
                            CustomerId = new Guid("b545fcbc-0c85-4f2e-a702-4ba5089f702a"),
                            CreditCardNumber = "6767-2263-8324-0297-982",
                            Email = "Enrique.Fay@hotmail.com",
                            Name = "Enrique Fay"
                        },
                        new
                        {
                            CustomerId = new Guid("787d76ed-e829-44c2-a588-7380d05cdfa8"),
                            CreditCardNumber = "6485-6228-1450-0257-6871",
                            Email = "Ella.Wilkinson@yahoo.com",
                            Name = "Ella Wilkinson"
                        },
                        new
                        {
                            CustomerId = new Guid("f5b83448-c1f4-4522-8066-5c1e040bf353"),
                            CreditCardNumber = "6767-9596-8116-1142-28",
                            Email = "Gretchen94@yahoo.com",
                            Name = "Gretchen Gleichner"
                        },
                        new
                        {
                            CustomerId = new Guid("ad95c910-fa23-488a-92c2-9049cdbe2fcc"),
                            CreditCardNumber = "6393-3091-0837-7232",
                            Email = "Alton_Mueller66@yahoo.com",
                            Name = "Alton Mueller"
                        },
                        new
                        {
                            CustomerId = new Guid("7100f416-ad96-4f5e-a025-5bac30ba364b"),
                            CreditCardNumber = "6771-8913-8894-0195",
                            Email = "Nathaniel_Wiza@hotmail.com",
                            Name = "Nathaniel Wiza"
                        });
                });

            modelBuilder.Entity("P03_SalesDatabase.Data.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasDefaultValue("No description");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("88c73c61-3fc6-4c7d-8ca5-24ebe4c2998a"),
                            Name = "Ergonomic Concrete Cheese",
                            Price = 6644.505851616420000m,
                            Quantity = 368.99594f
                        },
                        new
                        {
                            ProductId = new Guid("a66bd49e-3c44-4629-82b7-a0218f947499"),
                            Name = "Awesome Plastic Ball",
                            Price = 1228.473554442930000m,
                            Quantity = 903.44025f
                        },
                        new
                        {
                            ProductId = new Guid("11328793-cf9b-471f-8240-e44e3e6a7ace"),
                            Name = "Refined Metal Towels",
                            Price = 7829.531180199570000m,
                            Quantity = 100.7725f
                        },
                        new
                        {
                            ProductId = new Guid("839bff32-6709-4337-a655-1321663944c8"),
                            Name = "Handmade Plastic Hat",
                            Price = 6784.921879834640000m,
                            Quantity = 736.949f
                        },
                        new
                        {
                            ProductId = new Guid("0d6c1b39-abff-49f5-8231-09132aeddea2"),
                            Name = "Unbranded Fresh Shoes",
                            Price = 8013.503452152360000m,
                            Quantity = 181.00146f
                        },
                        new
                        {
                            ProductId = new Guid("9c7f1eb4-626f-4667-a299-b9e954e7ee78"),
                            Name = "Gorgeous Wooden Shirt",
                            Price = 949.591153792370000m,
                            Quantity = 222.10248f
                        },
                        new
                        {
                            ProductId = new Guid("377322eb-f59e-479e-b4f2-69e115b0a2e7"),
                            Name = "Ergonomic Metal Chicken",
                            Price = 491.8371831744820000m,
                            Quantity = 402.1906f
                        },
                        new
                        {
                            ProductId = new Guid("c6c5d479-cbc8-4e8a-859e-6c69990b9684"),
                            Name = "Handcrafted Metal Ball",
                            Price = 3170.525092092880000m,
                            Quantity = 727.4399f
                        },
                        new
                        {
                            ProductId = new Guid("79b8e14d-7d45-424a-8d18-16684a24f583"),
                            Name = "Practical Metal Pants",
                            Price = 4051.064780816790000m,
                            Quantity = 587.2252f
                        },
                        new
                        {
                            ProductId = new Guid("33c6d0e7-0fb9-4145-8da4-1546d0b20483"),
                            Name = "Licensed Granite Bike",
                            Price = 1035.383969859620000m,
                            Quantity = 885.1648f
                        },
                        new
                        {
                            ProductId = new Guid("78f3d96e-9e40-4772-bef7-eb50713792ab"),
                            Name = "Tasty Frozen Mouse",
                            Price = 5739.746762074960000m,
                            Quantity = 221.89673f
                        },
                        new
                        {
                            ProductId = new Guid("14a122d8-ce72-4dde-95e1-f4ab9273cdaf"),
                            Name = "Handcrafted Granite Chips",
                            Price = 4611.0240829110000m,
                            Quantity = 69.25823f
                        },
                        new
                        {
                            ProductId = new Guid("0ca5a339-85b0-4426-9324-0210c34b9975"),
                            Name = "Generic Concrete Pizza",
                            Price = 9152.833210086270000m,
                            Quantity = 303.43155f
                        },
                        new
                        {
                            ProductId = new Guid("018f9b79-e0e7-4164-9131-1a33106c141e"),
                            Name = "Handmade Granite Salad",
                            Price = 2810.82446499710000m,
                            Quantity = 368.97278f
                        },
                        new
                        {
                            ProductId = new Guid("27f79389-dc63-4fd4-9124-015814765975"),
                            Name = "Licensed Soft Pizza",
                            Price = 6533.47001020790000m,
                            Quantity = 688.5904f
                        },
                        new
                        {
                            ProductId = new Guid("714dcc9b-e1c8-4bb4-9ad9-7e6fa466a8ba"),
                            Name = "Practical Cotton Sausages",
                            Price = 5797.135690116220000m,
                            Quantity = 874.4079f
                        },
                        new
                        {
                            ProductId = new Guid("5cdfa3ed-2eef-4d77-923a-208c0d43bce5"),
                            Name = "Practical Granite Tuna",
                            Price = 1741.132555024610000m,
                            Quantity = 26.41305f
                        },
                        new
                        {
                            ProductId = new Guid("33e34ac5-9222-461c-a728-ba22b3121c5d"),
                            Name = "Gorgeous Frozen Sausages",
                            Price = 1165.658533016490000m,
                            Quantity = 327.988f
                        },
                        new
                        {
                            ProductId = new Guid("25dd6fc6-6c36-4078-80c9-da2cec40d009"),
                            Name = "Handcrafted Cotton Pants",
                            Price = 4899.4249745070000m,
                            Quantity = 31.891691f
                        },
                        new
                        {
                            ProductId = new Guid("b3db3909-be26-4e50-a4a6-b552d26f8c47"),
                            Name = "Gorgeous Soft Tuna",
                            Price = 403.1992855746490000m,
                            Quantity = 263.8643f
                        },
                        new
                        {
                            ProductId = new Guid("0a6907a4-f344-4e10-82a7-024a0700a2f2"),
                            Name = "Practical Metal Cheese",
                            Price = 9766.40921464080000m,
                            Quantity = 813.8265f
                        },
                        new
                        {
                            ProductId = new Guid("fdef68c1-5208-4c0c-ab44-9dc1564628b4"),
                            Name = "Rustic Granite Ball",
                            Price = 4646.882831872480000m,
                            Quantity = 936.08136f
                        },
                        new
                        {
                            ProductId = new Guid("9f22a7d4-b06b-4349-83be-7a42df5ef1bc"),
                            Name = "Awesome Cotton Bacon",
                            Price = 7588.453467624570000m,
                            Quantity = 106.783485f
                        },
                        new
                        {
                            ProductId = new Guid("a8b249b0-f986-42b7-b1c6-4eade2c64385"),
                            Name = "Fantastic Granite Towels",
                            Price = 1098.789701811910000m,
                            Quantity = 882.8381f
                        },
                        new
                        {
                            ProductId = new Guid("a62463f8-4a7d-4250-9301-4052a25b589c"),
                            Name = "Intelligent Cotton Fish",
                            Price = 44.9955901075050000m,
                            Quantity = 897.97906f
                        },
                        new
                        {
                            ProductId = new Guid("7c569d4a-ff6a-4ac9-9316-966b78a3f360"),
                            Name = "Generic Fresh Shirt",
                            Price = 1654.177301270350000m,
                            Quantity = 439.84396f
                        },
                        new
                        {
                            ProductId = new Guid("8c20c01e-e876-4acc-ad11-625a758262b5"),
                            Name = "Fantastic Rubber Salad",
                            Price = 2445.560236133620000m,
                            Quantity = 408.36218f
                        },
                        new
                        {
                            ProductId = new Guid("cd4b5b9f-057d-4264-9948-7a477443b491"),
                            Name = "Awesome Rubber Salad",
                            Price = 5149.778677312840000m,
                            Quantity = 184.50395f
                        },
                        new
                        {
                            ProductId = new Guid("80ae9339-65fe-479c-8b75-01bfcd33b8d5"),
                            Name = "Rustic Rubber Mouse",
                            Price = 3252.732414327270000m,
                            Quantity = 74.4556f
                        },
                        new
                        {
                            ProductId = new Guid("20c793c5-89bf-40e4-9d9a-221f4d46a8de"),
                            Name = "Ergonomic Cotton Car",
                            Price = 3331.214647642560000m,
                            Quantity = 694.36005f
                        },
                        new
                        {
                            ProductId = new Guid("ad39edb2-66a8-4001-8f1c-14b28f6b0384"),
                            Name = "Refined Plastic Pizza",
                            Price = 2577.843891795450000m,
                            Quantity = 978.5447f
                        },
                        new
                        {
                            ProductId = new Guid("979db3b5-aebd-43d0-87b4-97d507d4165d"),
                            Name = "Generic Fresh Bacon",
                            Price = 5454.421495650580000m,
                            Quantity = 294.69992f
                        },
                        new
                        {
                            ProductId = new Guid("c9c0e111-dc00-4a2b-b611-bae73bc5e378"),
                            Name = "Practical Metal Ball",
                            Price = 3440.621281804730000m,
                            Quantity = 751.7017f
                        },
                        new
                        {
                            ProductId = new Guid("ea23931a-36cc-4a9c-b042-bf99bf8eb924"),
                            Name = "Intelligent Wooden Table",
                            Price = 7532.940074563820000m,
                            Quantity = 756.53613f
                        },
                        new
                        {
                            ProductId = new Guid("a2624c2d-aac1-4fb5-8bd0-8af55f21b6d6"),
                            Name = "Handcrafted Frozen Bike",
                            Price = 432.4530486614280000m,
                            Quantity = 333.32977f
                        },
                        new
                        {
                            ProductId = new Guid("1e80c00d-d050-4299-9a34-3d123585f196"),
                            Name = "Practical Plastic Bike",
                            Price = 990.9037429835660000m,
                            Quantity = 983.72894f
                        },
                        new
                        {
                            ProductId = new Guid("f922cb95-c4c2-4331-b564-3423c5006aea"),
                            Name = "Sleek Steel Shoes",
                            Price = 7825.485935272210000m,
                            Quantity = 855.5681f
                        },
                        new
                        {
                            ProductId = new Guid("8825853c-37d0-4de5-bcae-94cfd5a57f2f"),
                            Name = "Unbranded Granite Chair",
                            Price = 6014.941641055650000m,
                            Quantity = 822.5766f
                        },
                        new
                        {
                            ProductId = new Guid("4ec94b80-27f1-467c-a80b-dabd27018548"),
                            Name = "Ergonomic Concrete Salad",
                            Price = 941.126082857790000m,
                            Quantity = 251.35135f
                        },
                        new
                        {
                            ProductId = new Guid("fe787156-2714-4291-bc66-e5391e8e428e"),
                            Name = "Incredible Granite Towels",
                            Price = 1032.622287708980000m,
                            Quantity = 624.5028f
                        });
                });

            modelBuilder.Entity("P03_SalesDatabase.Data.Models.Sale", b =>
                {
                    b.Property<Guid>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Customer");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Product");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Store");

                    b.HasKey("SaleId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StoreId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            SaleId = new Guid("7f6a3d7f-2cfa-4d93-9b2a-523793fa05ec"),
                            CustomerId = new Guid("221fde44-da7e-40a4-a8b6-b4453d968064"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("377322eb-f59e-479e-b4f2-69e115b0a2e7"),
                            StoreId = new Guid("97d1c0da-e91e-4327-9721-5e0082424785")
                        },
                        new
                        {
                            SaleId = new Guid("2a6724fe-401a-4032-9db4-04dfe468bc88"),
                            CustomerId = new Guid("8d8bdf71-2da2-4ad1-a834-301a32bfa72f"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("11328793-cf9b-471f-8240-e44e3e6a7ace"),
                            StoreId = new Guid("b21e3b26-0f8a-4365-aaad-74fecbd6f76c")
                        },
                        new
                        {
                            SaleId = new Guid("f13e3a39-7a2b-4c52-9c61-964d1dc82c7a"),
                            CustomerId = new Guid("221fde44-da7e-40a4-a8b6-b4453d968064"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("b3db3909-be26-4e50-a4a6-b552d26f8c47"),
                            StoreId = new Guid("f9467a16-fdb3-4c10-9334-b6318d1dce3a")
                        },
                        new
                        {
                            SaleId = new Guid("bf7ae89b-2bb5-4316-be9f-3f860ff33ebf"),
                            CustomerId = new Guid("95faa7e8-4fac-46f2-9642-2809bb52fbf3"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("9c7f1eb4-626f-4667-a299-b9e954e7ee78"),
                            StoreId = new Guid("b21e3b26-0f8a-4365-aaad-74fecbd6f76c")
                        },
                        new
                        {
                            SaleId = new Guid("4da9558f-a3eb-4fa8-866e-0d296b45d81f"),
                            CustomerId = new Guid("221fde44-da7e-40a4-a8b6-b4453d968064"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("33e34ac5-9222-461c-a728-ba22b3121c5d"),
                            StoreId = new Guid("f541d2e4-9bda-49b3-8947-f3bf74101013")
                        },
                        new
                        {
                            SaleId = new Guid("c2f250f8-32fa-4bd1-98a4-1a58273b71be"),
                            CustomerId = new Guid("8d8bdf71-2da2-4ad1-a834-301a32bfa72f"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("27f79389-dc63-4fd4-9124-015814765975"),
                            StoreId = new Guid("27823491-d439-4763-b74d-cb43902defc2")
                        },
                        new
                        {
                            SaleId = new Guid("3e2df30e-7862-4b31-8f58-e1a386eada77"),
                            CustomerId = new Guid("76357a45-a4c8-44ad-8cf2-3b4aae0a7fa5"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("33e34ac5-9222-461c-a728-ba22b3121c5d"),
                            StoreId = new Guid("0b9241d4-edc0-4687-9af4-96460b5ff0c2")
                        },
                        new
                        {
                            SaleId = new Guid("72a76576-f3b3-40a3-9537-3bb52ceec94c"),
                            CustomerId = new Guid("76357a45-a4c8-44ad-8cf2-3b4aae0a7fa5"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("b3db3909-be26-4e50-a4a6-b552d26f8c47"),
                            StoreId = new Guid("27823491-d439-4763-b74d-cb43902defc2")
                        },
                        new
                        {
                            SaleId = new Guid("e2e4f978-ceb0-477f-9713-ad47260aa108"),
                            CustomerId = new Guid("cb583612-f843-4997-8f4f-1ea30345a571"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("377322eb-f59e-479e-b4f2-69e115b0a2e7"),
                            StoreId = new Guid("c79fbd79-d309-4285-81ee-b7659740e4ab")
                        },
                        new
                        {
                            SaleId = new Guid("f9007a73-bbf5-4b0a-81ed-d564deab4926"),
                            CustomerId = new Guid("cb583612-f843-4997-8f4f-1ea30345a571"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("11328793-cf9b-471f-8240-e44e3e6a7ace"),
                            StoreId = new Guid("27823491-d439-4763-b74d-cb43902defc2")
                        },
                        new
                        {
                            SaleId = new Guid("8f6a2206-4bd2-4d41-b02c-ed25ca4f5047"),
                            CustomerId = new Guid("696c34e8-9b3d-4d9e-b060-44f6f0869acf"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("714dcc9b-e1c8-4bb4-9ad9-7e6fa466a8ba"),
                            StoreId = new Guid("7e2567da-01bb-4a31-854f-ebda149a6bf4")
                        },
                        new
                        {
                            SaleId = new Guid("3ab1bf02-9018-4721-9a28-b197caac8ca3"),
                            CustomerId = new Guid("ab938cad-6465-4026-9ef3-3d9b30e20af9"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("11328793-cf9b-471f-8240-e44e3e6a7ace"),
                            StoreId = new Guid("7e2567da-01bb-4a31-854f-ebda149a6bf4")
                        },
                        new
                        {
                            SaleId = new Guid("f834fa31-e0aa-431c-aefa-0a96854cc014"),
                            CustomerId = new Guid("221fde44-da7e-40a4-a8b6-b4453d968064"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("0ca5a339-85b0-4426-9324-0210c34b9975"),
                            StoreId = new Guid("f9467a16-fdb3-4c10-9334-b6318d1dce3a")
                        },
                        new
                        {
                            SaleId = new Guid("139e2ddf-a445-458e-80a3-ecca0f1cd4f6"),
                            CustomerId = new Guid("76357a45-a4c8-44ad-8cf2-3b4aae0a7fa5"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("11328793-cf9b-471f-8240-e44e3e6a7ace"),
                            StoreId = new Guid("c79fbd79-d309-4285-81ee-b7659740e4ab")
                        },
                        new
                        {
                            SaleId = new Guid("379d6754-2385-47bf-9893-a07e2013f680"),
                            CustomerId = new Guid("221fde44-da7e-40a4-a8b6-b4453d968064"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("b3db3909-be26-4e50-a4a6-b552d26f8c47"),
                            StoreId = new Guid("f541d2e4-9bda-49b3-8947-f3bf74101013")
                        },
                        new
                        {
                            SaleId = new Guid("1f29d50b-de0c-4b9a-ae16-48d24b5b0c22"),
                            CustomerId = new Guid("b545fcbc-0c85-4f2e-a702-4ba5089f702a"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("c9c0e111-dc00-4a2b-b611-bae73bc5e378"),
                            StoreId = new Guid("988de305-599c-4aa5-9bc1-cc570c436d72")
                        },
                        new
                        {
                            SaleId = new Guid("32a0f88b-1c98-4ed7-a31c-6c3c368a2477"),
                            CustomerId = new Guid("2585d500-f84c-42ad-91f5-aabc7a001160"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("c6c5d479-cbc8-4e8a-859e-6c69990b9684"),
                            StoreId = new Guid("f541d2e4-9bda-49b3-8947-f3bf74101013")
                        },
                        new
                        {
                            SaleId = new Guid("49d0f78c-f189-4413-a10f-bc96d9c59300"),
                            CustomerId = new Guid("cb583612-f843-4997-8f4f-1ea30345a571"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("a62463f8-4a7d-4250-9301-4052a25b589c"),
                            StoreId = new Guid("988de305-599c-4aa5-9bc1-cc570c436d72")
                        },
                        new
                        {
                            SaleId = new Guid("c2c7dbcf-6e7d-46db-ac6b-ddeff9cc8c10"),
                            CustomerId = new Guid("f5b83448-c1f4-4522-8066-5c1e040bf353"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("5cdfa3ed-2eef-4d77-923a-208c0d43bce5"),
                            StoreId = new Guid("f541d2e4-9bda-49b3-8947-f3bf74101013")
                        },
                        new
                        {
                            SaleId = new Guid("5f3b54db-c342-4c41-acfd-17d01a06544c"),
                            CustomerId = new Guid("7100f416-ad96-4f5e-a025-5bac30ba364b"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("78f3d96e-9e40-4772-bef7-eb50713792ab"),
                            StoreId = new Guid("323b5fe8-df4d-424f-8d8a-48d8cea91fbe")
                        },
                        new
                        {
                            SaleId = new Guid("1a32eb2b-e3d6-41d2-81da-585b79c74cfd"),
                            CustomerId = new Guid("f5b83448-c1f4-4522-8066-5c1e040bf353"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("4ec94b80-27f1-467c-a80b-dabd27018548"),
                            StoreId = new Guid("70c83c1c-9842-4636-aa34-d61d610add23")
                        },
                        new
                        {
                            SaleId = new Guid("751a9d10-8122-4265-baa0-c0c4c82cf0c9"),
                            CustomerId = new Guid("cb583612-f843-4997-8f4f-1ea30345a571"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("fe787156-2714-4291-bc66-e5391e8e428e"),
                            StoreId = new Guid("cc9b7034-4c22-4053-ba0c-2241c0b4e8ec")
                        },
                        new
                        {
                            SaleId = new Guid("6dac4c1b-e58e-4c38-b280-e0f4a504795d"),
                            CustomerId = new Guid("17833e28-fa62-44e9-af89-02115ce53ed6"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("c9c0e111-dc00-4a2b-b611-bae73bc5e378"),
                            StoreId = new Guid("7e2567da-01bb-4a31-854f-ebda149a6bf4")
                        },
                        new
                        {
                            SaleId = new Guid("7a61fc4c-0d57-4bf9-b190-94fd761f58e2"),
                            CustomerId = new Guid("2f350e0f-1e05-489e-a534-d3dbccb4a549"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("979db3b5-aebd-43d0-87b4-97d507d4165d"),
                            StoreId = new Guid("c79fbd79-d309-4285-81ee-b7659740e4ab")
                        },
                        new
                        {
                            SaleId = new Guid("765be0be-6f72-4e7b-b038-1f1d774b3322"),
                            CustomerId = new Guid("cb583612-f843-4997-8f4f-1ea30345a571"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("27f79389-dc63-4fd4-9124-015814765975"),
                            StoreId = new Guid("106ba425-7a45-44c7-9cf1-3e1d2ca3bebf")
                        },
                        new
                        {
                            SaleId = new Guid("53b9269e-d268-47b4-8e39-92a3338094e3"),
                            CustomerId = new Guid("da6ea412-8e15-4056-9920-c9c278f7592d"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("1e80c00d-d050-4299-9a34-3d123585f196"),
                            StoreId = new Guid("d630fbee-387f-481c-b089-fc7f83635171")
                        },
                        new
                        {
                            SaleId = new Guid("73ff1e42-f98f-41ce-81cb-0ff31ab93ac2"),
                            CustomerId = new Guid("7100f416-ad96-4f5e-a025-5bac30ba364b"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("839bff32-6709-4337-a655-1321663944c8"),
                            StoreId = new Guid("b21e3b26-0f8a-4365-aaad-74fecbd6f76c")
                        },
                        new
                        {
                            SaleId = new Guid("cd8e99b5-7c87-4e3d-b982-51ca2d45d090"),
                            CustomerId = new Guid("221fde44-da7e-40a4-a8b6-b4453d968064"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("c6c5d479-cbc8-4e8a-859e-6c69990b9684"),
                            StoreId = new Guid("f541d2e4-9bda-49b3-8947-f3bf74101013")
                        },
                        new
                        {
                            SaleId = new Guid("3a27fc7e-197f-42f4-bc39-afbead3aa28d"),
                            CustomerId = new Guid("16aeae9f-824e-470b-ab86-109913afa19f"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("11328793-cf9b-471f-8240-e44e3e6a7ace"),
                            StoreId = new Guid("d630fbee-387f-481c-b089-fc7f83635171")
                        },
                        new
                        {
                            SaleId = new Guid("3380601f-ca54-4c8b-84cf-7342aaa773b9"),
                            CustomerId = new Guid("009762af-d785-452f-b238-5b19054b80bc"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("714dcc9b-e1c8-4bb4-9ad9-7e6fa466a8ba"),
                            StoreId = new Guid("c79fbd79-d309-4285-81ee-b7659740e4ab")
                        });
                });

            modelBuilder.Entity("P03_SalesDatabase.Data.Models.Store", b =>
                {
                    b.Property<Guid>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("StoreId");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            StoreId = new Guid("27823491-d439-4763-b74d-cb43902defc2"),
                            Name = "Corwin and Sons"
                        },
                        new
                        {
                            StoreId = new Guid("0b9241d4-edc0-4687-9af4-96460b5ff0c2"),
                            Name = "Gerlach, Von and Dare"
                        },
                        new
                        {
                            StoreId = new Guid("b21e3b26-0f8a-4365-aaad-74fecbd6f76c"),
                            Name = "Lindgren and Sons"
                        },
                        new
                        {
                            StoreId = new Guid("988de305-599c-4aa5-9bc1-cc570c436d72"),
                            Name = "Swaniawski, Christiansen and Zboncak"
                        },
                        new
                        {
                            StoreId = new Guid("f9467a16-fdb3-4c10-9334-b6318d1dce3a"),
                            Name = "Ondricka - Homenick"
                        },
                        new
                        {
                            StoreId = new Guid("c79fbd79-d309-4285-81ee-b7659740e4ab"),
                            Name = "Satterfield, Paucek and Reichel"
                        },
                        new
                        {
                            StoreId = new Guid("97d1c0da-e91e-4327-9721-5e0082424785"),
                            Name = "Bogisich, Labadie and Lebsack"
                        },
                        new
                        {
                            StoreId = new Guid("f541d2e4-9bda-49b3-8947-f3bf74101013"),
                            Name = "Hintz - Bradtke"
                        },
                        new
                        {
                            StoreId = new Guid("e339c877-67d7-4048-b6ef-341b3becc31c"),
                            Name = "Schroeder and Sons"
                        },
                        new
                        {
                            StoreId = new Guid("7e2567da-01bb-4a31-854f-ebda149a6bf4"),
                            Name = "Gorczany Group"
                        },
                        new
                        {
                            StoreId = new Guid("106ba425-7a45-44c7-9cf1-3e1d2ca3bebf"),
                            Name = "Jaskolski - Hudson"
                        },
                        new
                        {
                            StoreId = new Guid("9d46c85e-4ce2-4468-bdb1-eaba744849fa"),
                            Name = "Wunsch, Kassulke and Sauer"
                        },
                        new
                        {
                            StoreId = new Guid("273eed76-7715-47bc-bec7-983a25949339"),
                            Name = "Lang and Sons"
                        },
                        new
                        {
                            StoreId = new Guid("cc9b7034-4c22-4053-ba0c-2241c0b4e8ec"),
                            Name = "Kirlin - Emmerich"
                        },
                        new
                        {
                            StoreId = new Guid("65497ebb-6dc1-4bee-83de-9f9a3cb89330"),
                            Name = "Douglas - Turner"
                        },
                        new
                        {
                            StoreId = new Guid("88b105c4-712f-4df4-8a2e-6aec53182f7a"),
                            Name = "Torp LLC"
                        },
                        new
                        {
                            StoreId = new Guid("70c83c1c-9842-4636-aa34-d61d610add23"),
                            Name = "Farrell, Ankunding and Berge"
                        },
                        new
                        {
                            StoreId = new Guid("1ad0e913-ecbb-43ea-a48f-eea323e62109"),
                            Name = "Maggio, Oberbrunner and Pouros"
                        },
                        new
                        {
                            StoreId = new Guid("d630fbee-387f-481c-b089-fc7f83635171"),
                            Name = "Bernier - Lindgren"
                        },
                        new
                        {
                            StoreId = new Guid("323b5fe8-df4d-424f-8d8a-48d8cea91fbe"),
                            Name = "O'Connell LLC"
                        });
                });

            modelBuilder.Entity("P03_SalesDatabase.Data.Models.Sale", b =>
                {
                    b.HasOne("P03_SalesDatabase.Data.Models.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P03_SalesDatabase.Data.Models.Product", "Product")
                        .WithMany("Sales")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P03_SalesDatabase.Data.Models.Store", "Store")
                        .WithMany("Sales")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("P03_SalesDatabase.Data.Models.Customer", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("P03_SalesDatabase.Data.Models.Product", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("P03_SalesDatabase.Data.Models.Store", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
