// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P01_StudentSystem.Data;

#nullable disable

namespace P01_StudentSystem.Migrations
{
    [DbContext(typeof(StudentSystemContext))]
    [Migration("20230415191225_StudentSystemMigration1")]
    partial class StudentSystemMigration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("P01_StudentSystem.Data.Models.Course", b =>
                {
                    b.Property<Guid>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = new Guid("a55bfc43-e263-4ca1-8a07-95809004a7f5"),
                            Description = "Beatae aliquam placeat qui a perferendis et quibusdam assumenda. Ut quaerat adipisci aut perspiciatis quod sint iure. Similique autem et autem. Assumenda rem rem voluptatem.",
                            EndDate = new DateTime(2023, 4, 28, 4, 32, 56, 611, DateTimeKind.Local).AddTicks(8092),
                            Name = "Triple-buffered high-level implementation",
                            Price = 223.448267701755950m,
                            StartDate = new DateTime(2023, 4, 16, 2, 38, 22, 336, DateTimeKind.Local).AddTicks(5448)
                        },
                        new
                        {
                            CourseId = new Guid("31495db1-4432-4cd8-ba69-8035ad6b51a7"),
                            Description = "Aspernatur quis aut culpa accusantium molestiae debitis quam et. Consectetur eum qui quia amet tempora amet. A at qui voluptas. Id qui officia esse et sunt ut error.",
                            EndDate = new DateTime(2023, 4, 29, 9, 59, 31, 13, DateTimeKind.Local).AddTicks(6003),
                            Name = "Stand-alone directional definition",
                            Price = 433.525480105108100m,
                            StartDate = new DateTime(2023, 4, 16, 8, 33, 18, 131, DateTimeKind.Local).AddTicks(4216)
                        },
                        new
                        {
                            CourseId = new Guid("bbc08b02-6dc7-4539-a67b-f50568eb9b76"),
                            Description = "Porro distinctio aut atque nam aut ab ipsa. Explicabo pariatur aut rem in unde nulla. Hic voluptas ut architecto ut accusantium iure qui.",
                            EndDate = new DateTime(2023, 4, 23, 0, 44, 51, 413, DateTimeKind.Local).AddTicks(3279),
                            Name = "Realigned executive instruction set",
                            Price = 176.560580817551750m,
                            StartDate = new DateTime(2023, 4, 16, 6, 1, 44, 476, DateTimeKind.Local).AddTicks(6484)
                        },
                        new
                        {
                            CourseId = new Guid("dbea9829-1c17-4c23-a7a7-981a43d2e59e"),
                            Description = "Quas aperiam asperiores. Vero ut libero corrupti quia. Et molestiae dolorem nobis facere quae debitis sint culpa.",
                            EndDate = new DateTime(2023, 4, 23, 8, 37, 22, 717, DateTimeKind.Local).AddTicks(1462),
                            Name = "Advanced asymmetric functionalities",
                            Price = 375.941239560830750m,
                            StartDate = new DateTime(2023, 4, 16, 10, 55, 33, 602, DateTimeKind.Local).AddTicks(2408)
                        },
                        new
                        {
                            CourseId = new Guid("579a1893-1669-4790-8d32-d432f436b440"),
                            Description = "Ipsum officiis voluptatibus distinctio nobis rerum beatae consectetur. Voluptas dolorum optio praesentium autem aliquam ut impedit sequi nesciunt. Fuga ut quo quo blanditiis est numquam eos beatae.",
                            EndDate = new DateTime(2023, 5, 5, 6, 54, 33, 977, DateTimeKind.Local).AddTicks(9350),
                            Name = "Reverse-engineered zero tolerance task-force",
                            Price = 262.905500625527300m,
                            StartDate = new DateTime(2023, 4, 16, 11, 37, 37, 785, DateTimeKind.Local).AddTicks(5084)
                        },
                        new
                        {
                            CourseId = new Guid("ef21e5c4-9251-441d-8b33-6c1302a9b8c5"),
                            Description = "Ut tenetur optio minima voluptatem omnis vero possimus. Autem laboriosam quo molestiae eligendi saepe quis non. Provident incidunt totam laboriosam recusandae facilis. Nemo qui aperiam. Odio nisi quis unde autem quisquam hic.",
                            EndDate = new DateTime(2023, 5, 8, 3, 36, 10, 278, DateTimeKind.Local).AddTicks(4346),
                            Name = "Total motivating concept",
                            Price = 105.823319808689600m,
                            StartDate = new DateTime(2023, 4, 16, 16, 23, 3, 856, DateTimeKind.Local).AddTicks(6241)
                        },
                        new
                        {
                            CourseId = new Guid("2118b5e5-367a-4fcb-95f3-d07bd6971691"),
                            Description = "Maxime dolorum aut qui quas quia similique. Dolor dolorem deserunt qui perferendis sint quo. In et et reiciendis sit qui. Voluptatibus rerum inventore odit ex assumenda aut et quaerat blanditiis. Quidem molestiae sint qui aliquid eum quia omnis voluptatum. Sint necessitatibus velit sunt placeat error suscipit et vel.",
                            EndDate = new DateTime(2023, 4, 22, 6, 18, 32, 696, DateTimeKind.Local).AddTicks(4167),
                            Name = "Cloned fault-tolerant emulation",
                            Price = 304.990742307768350m,
                            StartDate = new DateTime(2023, 4, 16, 4, 50, 35, 334, DateTimeKind.Local).AddTicks(5556)
                        },
                        new
                        {
                            CourseId = new Guid("93784236-c722-4add-9e12-a7361fdb3bd7"),
                            Description = "Modi incidunt beatae. Repellendus eos animi quia dolores ut eligendi. Nulla ad dignissimos. Quia ducimus illo. Excepturi aliquid ducimus ut ad voluptatem in et. Inventore et omnis voluptas vitae magnam nobis.",
                            EndDate = new DateTime(2023, 5, 11, 15, 6, 53, 687, DateTimeKind.Local).AddTicks(4749),
                            Name = "Persistent human-resource website",
                            Price = 412.567680735690800m,
                            StartDate = new DateTime(2023, 4, 15, 23, 19, 31, 474, DateTimeKind.Local).AddTicks(6880)
                        },
                        new
                        {
                            CourseId = new Guid("3e7becd1-76cb-43dd-a6fc-f1f17a7a37b1"),
                            Description = "Suscipit quis rerum et voluptates porro officia laboriosam eveniet. Natus qui facilis excepturi in impedit earum. Sed ut quia est ducimus totam sit autem et.",
                            EndDate = new DateTime(2023, 5, 4, 13, 28, 13, 576, DateTimeKind.Local).AddTicks(1069),
                            Name = "Object-based optimizing secured line",
                            Price = 332.616267308561900m,
                            StartDate = new DateTime(2023, 4, 16, 14, 43, 54, 944, DateTimeKind.Local).AddTicks(1998)
                        },
                        new
                        {
                            CourseId = new Guid("af28b460-cc1b-402a-b2eb-29ccca14d1dc"),
                            Description = "Eum officiis voluptatem qui qui quibusdam at ab. Inventore in veniam velit delectus eos. Non ea eos fugiat. Quos dicta id repellat est atque quia quia. Provident ullam aut.",
                            EndDate = new DateTime(2023, 5, 11, 19, 14, 38, 98, DateTimeKind.Local).AddTicks(7127),
                            Name = "Fundamental heuristic infrastructure",
                            Price = 482.849793148092800m,
                            StartDate = new DateTime(2023, 4, 16, 3, 31, 13, 372, DateTimeKind.Local).AddTicks(6343)
                        });
                });

            modelBuilder.Entity("P01_StudentSystem.Data.Models.Homework", b =>
                {
                    b.Property<Guid>("HomeworkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SubmissionTime")
                        .HasColumnType("datetime2");

                    b.HasKey("HomeworkId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("HomeworkSubmissions");

                    b.HasData(
                        new
                        {
                            HomeworkId = new Guid("8e0bc162-384c-428b-bff4-75bb687ee3ea"),
                            Content = "Officiis qui temporibus. Ad laboriosam quasi et ab distinctio non at. Sint saepe quibusdam facilis sequi.",
                            ContentType = "Application",
                            CourseId = new Guid("dbea9829-1c17-4c23-a7a7-981a43d2e59e"),
                            StudentId = new Guid("46c1edcf-a2ff-4058-99ed-f7a73eed038f"),
                            SubmissionTime = new DateTime(2023, 4, 9, 8, 50, 33, 902, DateTimeKind.Utc).AddTicks(7766)
                        },
                        new
                        {
                            HomeworkId = new Guid("8434acb3-01e6-489d-b93e-1b1ef4691188"),
                            Content = "Quasi occaecati id commodi ea quos quam atque aperiam. Sit qui aut fuga repellendus nam id. Quidem tempora deleniti et enim quae quam. Aut ullam modi corporis vitae velit ipsam quo voluptas.",
                            ContentType = "Application",
                            CourseId = new Guid("579a1893-1669-4790-8d32-d432f436b440"),
                            StudentId = new Guid("9829a10e-9afd-4787-a7e3-849e7974570e"),
                            SubmissionTime = new DateTime(2023, 4, 9, 21, 46, 47, 942, DateTimeKind.Utc).AddTicks(1447)
                        },
                        new
                        {
                            HomeworkId = new Guid("faa97b68-faa9-48e0-8221-b6125f6000dd"),
                            Content = "Ut similique deleniti omnis esse ullam eos quas ipsum. Aliquam maiores minima est et dolorum iure non. Sunt doloremque at soluta consectetur animi molestias vero ratione amet.",
                            ContentType = "Application",
                            CourseId = new Guid("93784236-c722-4add-9e12-a7361fdb3bd7"),
                            StudentId = new Guid("5df343f1-769a-4f05-9a66-df6d8cdac4da"),
                            SubmissionTime = new DateTime(2023, 4, 14, 2, 46, 42, 7, DateTimeKind.Utc).AddTicks(8619)
                        },
                        new
                        {
                            HomeworkId = new Guid("05bcad89-8828-4e21-98cc-7887eae61248"),
                            Content = "Et eum officia laborum aut aliquid et. Et praesentium optio dolor. Eum eveniet quia voluptas dolor eveniet exercitationem corrupti. Architecto perferendis voluptatibus laborum. Quaerat nam aut pariatur eligendi eum molestias quae.",
                            ContentType = "Pdf",
                            CourseId = new Guid("93784236-c722-4add-9e12-a7361fdb3bd7"),
                            StudentId = new Guid("cca72391-aaec-47ba-90c8-5d4935441652"),
                            SubmissionTime = new DateTime(2023, 4, 15, 15, 1, 26, 248, DateTimeKind.Utc).AddTicks(5424)
                        },
                        new
                        {
                            HomeworkId = new Guid("f7374033-f9ae-43af-8380-37784a435e32"),
                            Content = "Dolorum facilis facere mollitia. Sint est et quas. Et dolorem maxime.",
                            ContentType = "Zip",
                            CourseId = new Guid("93784236-c722-4add-9e12-a7361fdb3bd7"),
                            StudentId = new Guid("93230d81-d958-460e-bf3b-01072d29194c"),
                            SubmissionTime = new DateTime(2023, 4, 14, 15, 12, 47, 153, DateTimeKind.Utc).AddTicks(6228)
                        },
                        new
                        {
                            HomeworkId = new Guid("9dad962d-01cb-49be-9ae1-d08796c09f69"),
                            Content = "Aliquam omnis quia rerum doloremque aspernatur et autem. Voluptas vero nemo quis praesentium aut repudiandae. Est autem doloribus itaque voluptatem qui atque enim nostrum recusandae. Eum sint harum sint aut consequatur eum. Assumenda dignissimos adipisci doloremque rerum et facilis quisquam. Vel quia laudantium laboriosam est maxime debitis eveniet id.",
                            ContentType = "Application",
                            CourseId = new Guid("ef21e5c4-9251-441d-8b33-6c1302a9b8c5"),
                            StudentId = new Guid("9829a10e-9afd-4787-a7e3-849e7974570e"),
                            SubmissionTime = new DateTime(2023, 4, 15, 8, 38, 6, 591, DateTimeKind.Utc).AddTicks(5073)
                        },
                        new
                        {
                            HomeworkId = new Guid("4653d498-0740-476f-b3dc-7cfe6b8aaf5f"),
                            Content = "Et et commodi rerum et et porro. Totam et quibusdam ipsam nobis quis rerum. Sed tenetur est quae ullam ut neque tempora fuga. Est est amet sit laudantium quo ad eligendi quibusdam dolores. Et voluptatum id quam quaerat pariatur est.",
                            ContentType = "Application",
                            CourseId = new Guid("a55bfc43-e263-4ca1-8a07-95809004a7f5"),
                            StudentId = new Guid("cca72391-aaec-47ba-90c8-5d4935441652"),
                            SubmissionTime = new DateTime(2023, 4, 9, 11, 8, 12, 832, DateTimeKind.Utc).AddTicks(3444)
                        },
                        new
                        {
                            HomeworkId = new Guid("5a558009-6075-4ca2-b5de-96ef97120fe4"),
                            Content = "Eum ea dolorum. Quia explicabo et non. Ut corporis magnam et sit quibusdam veniam. Laudantium illum aut et omnis vel rerum hic nemo. Ipsa laudantium nostrum at cum id. Sit voluptates et.",
                            ContentType = "Pdf",
                            CourseId = new Guid("579a1893-1669-4790-8d32-d432f436b440"),
                            StudentId = new Guid("5df343f1-769a-4f05-9a66-df6d8cdac4da"),
                            SubmissionTime = new DateTime(2023, 4, 15, 15, 14, 28, 779, DateTimeKind.Utc).AddTicks(9903)
                        },
                        new
                        {
                            HomeworkId = new Guid("be2e00dc-5491-4e3a-af0f-6adf9fd40c7b"),
                            Content = "Pariatur nostrum excepturi. Eos non vitae sed aliquam. Sunt eos et quis.",
                            ContentType = "Pdf",
                            CourseId = new Guid("a55bfc43-e263-4ca1-8a07-95809004a7f5"),
                            StudentId = new Guid("9829a10e-9afd-4787-a7e3-849e7974570e"),
                            SubmissionTime = new DateTime(2023, 4, 12, 4, 24, 3, 37, DateTimeKind.Utc).AddTicks(7320)
                        },
                        new
                        {
                            HomeworkId = new Guid("42b47a9f-4ccb-4852-87cd-68cd3fec78bf"),
                            Content = "Dicta sed fugiat maiores delectus. Consequuntur accusamus ipsa quis odio cumque a quas. Et ut eaque minima minima nulla repudiandae cupiditate delectus.",
                            ContentType = "Zip",
                            CourseId = new Guid("31495db1-4432-4cd8-ba69-8035ad6b51a7"),
                            StudentId = new Guid("46c1edcf-a2ff-4058-99ed-f7a73eed038f"),
                            SubmissionTime = new DateTime(2023, 4, 10, 16, 47, 17, 101, DateTimeKind.Utc).AddTicks(8255)
                        },
                        new
                        {
                            HomeworkId = new Guid("f4bdf4a1-c181-47f8-852d-c104347580fc"),
                            Content = "Nisi et cumque. Soluta ut et accusamus eum dolorem. Architecto expedita soluta et possimus ad harum. Adipisci odio voluptatem officiis delectus non quidem.",
                            ContentType = "Zip",
                            CourseId = new Guid("93784236-c722-4add-9e12-a7361fdb3bd7"),
                            StudentId = new Guid("9d2d0672-292f-43d3-b24c-368a1eb46957"),
                            SubmissionTime = new DateTime(2023, 4, 10, 23, 30, 17, 625, DateTimeKind.Utc).AddTicks(1757)
                        },
                        new
                        {
                            HomeworkId = new Guid("80f1388f-1341-46e0-af4b-0cafc3a12827"),
                            Content = "Ducimus sed ratione eum dolores iure eos modi aliquid corrupti. Sint nesciunt et architecto eveniet nisi quod iste molestiae. Similique laboriosam vitae quisquam. Provident aspernatur et qui optio doloribus repudiandae.",
                            ContentType = "Zip",
                            CourseId = new Guid("a55bfc43-e263-4ca1-8a07-95809004a7f5"),
                            StudentId = new Guid("9829a10e-9afd-4787-a7e3-849e7974570e"),
                            SubmissionTime = new DateTime(2023, 4, 13, 6, 26, 19, 328, DateTimeKind.Utc).AddTicks(426)
                        },
                        new
                        {
                            HomeworkId = new Guid("86173897-c3f5-4a3c-8cb1-127e57415dc4"),
                            Content = "Esse ut veniam consequatur eius quibusdam aliquam doloribus eligendi rerum. Praesentium et eaque aut qui delectus animi nam. Quam enim minima. Fuga sequi voluptatem deleniti id sed et qui perferendis quidem. Commodi sed optio deserunt aut quas quae amet repudiandae.",
                            ContentType = "Zip",
                            CourseId = new Guid("a55bfc43-e263-4ca1-8a07-95809004a7f5"),
                            StudentId = new Guid("9829a10e-9afd-4787-a7e3-849e7974570e"),
                            SubmissionTime = new DateTime(2023, 4, 13, 21, 12, 7, 607, DateTimeKind.Utc).AddTicks(6350)
                        },
                        new
                        {
                            HomeworkId = new Guid("895f88e4-a4c1-42d1-ac2c-36e3a980b19e"),
                            Content = "Non aut et quia sint incidunt necessitatibus quo quis quia. Voluptas suscipit ad deserunt possimus sint. Sed vero ex reprehenderit eos.",
                            ContentType = "Application",
                            CourseId = new Guid("93784236-c722-4add-9e12-a7361fdb3bd7"),
                            StudentId = new Guid("5df343f1-769a-4f05-9a66-df6d8cdac4da"),
                            SubmissionTime = new DateTime(2023, 4, 9, 16, 41, 46, 18, DateTimeKind.Utc).AddTicks(7479)
                        },
                        new
                        {
                            HomeworkId = new Guid("96b156c3-7105-420f-8cf7-2871b8b24e89"),
                            Content = "Voluptate repudiandae error rerum eligendi magnam. Pariatur quasi quis reiciendis. Vitae sint quia sed delectus rerum autem ab error temporibus. Qui non et. Est quae recusandae ipsam sunt eum nesciunt est est. Quia possimus vel odit.",
                            ContentType = "Pdf",
                            CourseId = new Guid("93784236-c722-4add-9e12-a7361fdb3bd7"),
                            StudentId = new Guid("199f9874-80f9-4002-a392-69f55655acbc"),
                            SubmissionTime = new DateTime(2023, 4, 11, 1, 46, 4, 697, DateTimeKind.Utc).AddTicks(5976)
                        });
                });

            modelBuilder.Entity("P01_StudentSystem.Data.Models.Resource", b =>
                {
                    b.Property<Guid>("ResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ResourceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("ResourceId");

                    b.HasIndex("CourseId");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            ResourceId = new Guid("45fe0cba-3ac3-4df3-a093-74f1b73a1e7c"),
                            CourseId = new Guid("2118b5e5-367a-4fcb-95f3-d07bd6971691"),
                            Name = "repudiandae",
                            ResourceType = "Document",
                            Url = "https://jewel.info"
                        },
                        new
                        {
                            ResourceId = new Guid("a011565e-46ae-4360-a832-5d881d33f84c"),
                            CourseId = new Guid("2118b5e5-367a-4fcb-95f3-d07bd6971691"),
                            Name = "delectus",
                            ResourceType = "Document",
                            Url = "https://skylar.com"
                        },
                        new
                        {
                            ResourceId = new Guid("99e60778-a445-45ef-bf09-28fed1a045c4"),
                            CourseId = new Guid("dbea9829-1c17-4c23-a7a7-981a43d2e59e"),
                            Name = "aliquid",
                            ResourceType = "Video",
                            Url = "http://tanya.com"
                        },
                        new
                        {
                            ResourceId = new Guid("9cc5043e-21ec-4bc8-bbd2-44d2f5651c92"),
                            CourseId = new Guid("2118b5e5-367a-4fcb-95f3-d07bd6971691"),
                            Name = "ipsum",
                            ResourceType = "Video",
                            Url = "https://elwin.org"
                        },
                        new
                        {
                            ResourceId = new Guid("5891fd27-10f4-4d25-af39-e1e04a1ae7bb"),
                            CourseId = new Guid("579a1893-1669-4790-8d32-d432f436b440"),
                            Name = "fugit",
                            ResourceType = "Video",
                            Url = "https://jaquelin.org"
                        },
                        new
                        {
                            ResourceId = new Guid("849aeb08-2225-4068-a907-9af1cb2a6e2c"),
                            CourseId = new Guid("dbea9829-1c17-4c23-a7a7-981a43d2e59e"),
                            Name = "adipisci",
                            ResourceType = "Presentation",
                            Url = "https://floy.name"
                        },
                        new
                        {
                            ResourceId = new Guid("d5d09cde-1173-4dd1-b44e-8a196734720e"),
                            CourseId = new Guid("579a1893-1669-4790-8d32-d432f436b440"),
                            Name = "odio",
                            ResourceType = "Document",
                            Url = "https://margot.biz"
                        },
                        new
                        {
                            ResourceId = new Guid("27d40853-64ca-4232-b230-eab5e763ef05"),
                            CourseId = new Guid("31495db1-4432-4cd8-ba69-8035ad6b51a7"),
                            Name = "suscipit",
                            ResourceType = "Document",
                            Url = "http://flossie.org"
                        },
                        new
                        {
                            ResourceId = new Guid("66b5d7b7-ca64-4b53-bf01-8350347b15b1"),
                            CourseId = new Guid("31495db1-4432-4cd8-ba69-8035ad6b51a7"),
                            Name = "cupiditate",
                            ResourceType = "Document",
                            Url = "http://georgette.com"
                        },
                        new
                        {
                            ResourceId = new Guid("50709aba-30c4-4e82-8374-931ece2bedad"),
                            CourseId = new Guid("31495db1-4432-4cd8-ba69-8035ad6b51a7"),
                            Name = "eos",
                            ResourceType = "Presentation",
                            Url = "https://rita.biz"
                        });
                });

            modelBuilder.Entity("P01_StudentSystem.Data.Models.Student", b =>
                {
                    b.Property<Guid>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("RegisteredOn")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = new Guid("93230d81-d958-460e-bf3b-01072d29194c"),
                            Birthday = new DateTime(2003, 12, 6, 1, 7, 28, 762, DateTimeKind.Local).AddTicks(7333),
                            Name = "Cleta Satterfield",
                            PhoneNumber = "1-825-837-1350 x296",
                            RegisteredOn = new DateTime(2023, 1, 28, 0, 1, 8, 593, DateTimeKind.Local).AddTicks(7818)
                        },
                        new
                        {
                            StudentId = new Guid("9829a10e-9afd-4787-a7e3-849e7974570e"),
                            Birthday = new DateTime(2001, 2, 2, 8, 25, 12, 648, DateTimeKind.Local).AddTicks(5765),
                            Name = "Jasen Kling",
                            PhoneNumber = "1-470-472-6980",
                            RegisteredOn = new DateTime(2022, 11, 22, 12, 22, 12, 315, DateTimeKind.Local).AddTicks(9294)
                        },
                        new
                        {
                            StudentId = new Guid("79c8d31b-b182-452f-9b0a-c3532cc1df01"),
                            Birthday = new DateTime(1999, 9, 2, 22, 43, 54, 39, DateTimeKind.Local).AddTicks(691),
                            Name = "Whitney Reinger",
                            PhoneNumber = "348-439-6608 x3904",
                            RegisteredOn = new DateTime(2023, 3, 3, 1, 34, 28, 373, DateTimeKind.Local).AddTicks(8965)
                        },
                        new
                        {
                            StudentId = new Guid("a3417ce7-1b6e-4d4e-9bd0-e4b6c7fcb277"),
                            Birthday = new DateTime(1993, 9, 11, 16, 48, 14, 524, DateTimeKind.Local).AddTicks(3921),
                            Name = "Deangelo Romaguera",
                            PhoneNumber = "(397) 619-1456",
                            RegisteredOn = new DateTime(2023, 1, 3, 20, 28, 59, 472, DateTimeKind.Local).AddTicks(4968)
                        },
                        new
                        {
                            StudentId = new Guid("199f9874-80f9-4002-a392-69f55655acbc"),
                            Birthday = new DateTime(2000, 8, 10, 1, 13, 37, 43, DateTimeKind.Local).AddTicks(2310),
                            Name = "Mattie Lynch",
                            PhoneNumber = "914.808.7330",
                            RegisteredOn = new DateTime(2023, 4, 14, 1, 47, 7, 222, DateTimeKind.Local).AddTicks(6067)
                        },
                        new
                        {
                            StudentId = new Guid("46c1edcf-a2ff-4058-99ed-f7a73eed038f"),
                            Birthday = new DateTime(1999, 4, 11, 0, 44, 25, 482, DateTimeKind.Local).AddTicks(40),
                            Name = "Jannie Schulist",
                            PhoneNumber = "1-885-978-1480 x0178",
                            RegisteredOn = new DateTime(2022, 10, 18, 5, 40, 2, 778, DateTimeKind.Local).AddTicks(7739)
                        },
                        new
                        {
                            StudentId = new Guid("9d2d0672-292f-43d3-b24c-368a1eb46957"),
                            Birthday = new DateTime(2000, 11, 7, 10, 7, 58, 261, DateTimeKind.Local).AddTicks(4287),
                            Name = "Marilyne Hickle",
                            PhoneNumber = "895-271-8789 x4548",
                            RegisteredOn = new DateTime(2022, 5, 14, 12, 18, 43, 479, DateTimeKind.Local).AddTicks(6481)
                        },
                        new
                        {
                            StudentId = new Guid("cca72391-aaec-47ba-90c8-5d4935441652"),
                            Birthday = new DateTime(2004, 2, 24, 0, 23, 26, 897, DateTimeKind.Local).AddTicks(6649),
                            Name = "Nathaniel Rohan",
                            PhoneNumber = "329-865-1654",
                            RegisteredOn = new DateTime(2022, 9, 1, 0, 11, 17, 236, DateTimeKind.Local).AddTicks(1675)
                        },
                        new
                        {
                            StudentId = new Guid("5922cebd-7e75-40f2-8cbb-8db57b2a67e1"),
                            Birthday = new DateTime(1995, 1, 20, 8, 38, 24, 25, DateTimeKind.Local).AddTicks(5857),
                            Name = "Alford Willms",
                            PhoneNumber = "603-714-8697 x6429",
                            RegisteredOn = new DateTime(2022, 12, 10, 6, 59, 50, 829, DateTimeKind.Local).AddTicks(1009)
                        },
                        new
                        {
                            StudentId = new Guid("5df343f1-769a-4f05-9a66-df6d8cdac4da"),
                            Birthday = new DateTime(1995, 8, 18, 5, 49, 50, 912, DateTimeKind.Local).AddTicks(8454),
                            Name = "Kory Quitzon",
                            PhoneNumber = "1-349-961-1802",
                            RegisteredOn = new DateTime(2022, 12, 12, 19, 36, 32, 390, DateTimeKind.Local).AddTicks(1692)
                        });
                });

            modelBuilder.Entity("P01_StudentSystem.Data.Models.StudentCourse", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("StudentCourses");

                    b.HasData(
                        new
                        {
                            StudentId = new Guid("46c1edcf-a2ff-4058-99ed-f7a73eed038f"),
                            CourseId = new Guid("579a1893-1669-4790-8d32-d432f436b440")
                        },
                        new
                        {
                            StudentId = new Guid("9d2d0672-292f-43d3-b24c-368a1eb46957"),
                            CourseId = new Guid("2118b5e5-367a-4fcb-95f3-d07bd6971691")
                        },
                        new
                        {
                            StudentId = new Guid("5922cebd-7e75-40f2-8cbb-8db57b2a67e1"),
                            CourseId = new Guid("bbc08b02-6dc7-4539-a67b-f50568eb9b76")
                        },
                        new
                        {
                            StudentId = new Guid("9829a10e-9afd-4787-a7e3-849e7974570e"),
                            CourseId = new Guid("2118b5e5-367a-4fcb-95f3-d07bd6971691")
                        },
                        new
                        {
                            StudentId = new Guid("a3417ce7-1b6e-4d4e-9bd0-e4b6c7fcb277"),
                            CourseId = new Guid("bbc08b02-6dc7-4539-a67b-f50568eb9b76")
                        });
                });

            modelBuilder.Entity("P01_StudentSystem.Data.Models.Homework", b =>
                {
                    b.HasOne("P01_StudentSystem.Data.Models.Course", "Course")
                        .WithMany("HomeworkSubmissions")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P01_StudentSystem.Data.Models.Student", "Student")
                        .WithMany("HomeworkSubmissions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("P01_StudentSystem.Data.Models.Resource", b =>
                {
                    b.HasOne("P01_StudentSystem.Data.Models.Course", "Course")
                        .WithMany("Resources")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("P01_StudentSystem.Data.Models.StudentCourse", b =>
                {
                    b.HasOne("P01_StudentSystem.Data.Models.Course", "Course")
                        .WithMany("StudentCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P01_StudentSystem.Data.Models.Student", "Student")
                        .WithMany("StudentCourses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("P01_StudentSystem.Data.Models.Course", b =>
                {
                    b.Navigation("HomeworkSubmissions");

                    b.Navigation("Resources");

                    b.Navigation("StudentCourses");
                });

            modelBuilder.Entity("P01_StudentSystem.Data.Models.Student", b =>
                {
                    b.Navigation("HomeworkSubmissions");

                    b.Navigation("StudentCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
